from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

attendees = [
    ('YU ARAKAWA', 'Consultant', 'IBM Japan, Ltd.'),
    ('Suli Abas', 'Business Development Manager', 'NSIGHT, INC.'),
    ('Katrina Acebedo', 'Data Architect', 'The Hershey Company'),
    ('NTT DATA Acuna Delaveau', 'Directora Enterprise Solution', 'NTT DATA Chile'),
    ('Laura Adare', 'Manager/Head of Dept', 'State of Louisiana'),
    ('Dhruv Aggarwal', "Partner Business Officer to SAP's Chi…", 'SAP SE'),
    ('Yeshu Aggarwal', 'Principal Value Advisor', 'SAP Canada'),
    ('Mukul Agrawal', 'IT Director', 'Cimpress USA Incorporated'),
    ('Lucia Aguilar Ledezma', 'RISE Business Developer', 'SAP Costa Rica, S.A.'),
    ('Saritha Aguru', 'Service Delivery & Product M…', 'Ernst & Young'),
    ('Takuya Akatsuka', 'GM', '株式会社リクルート'),
    ('Zia Akbar', 'Sr Architect', 'Jabil Circuit, Inc. c/o Compaq'),
    ('Ram Akella', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Kash Al Aziz', 'Global Head, Corporate Seg…', 'SAP MENA LLC'),
    ('Ebenezer Aladeojebi', 'Product Manager', 'J.P Morgan Chase & Co.'),
    ('Torsten Albert', 'VP - Head of CPIT Technology Servic…', 'SAP SE'),
    ('Steven Albor Jr', 'BTP…', 'SAP America Public Sec.(Newtown Sq)'),
    ('Cristian Ali', 'PES Head MCLAC', 'SAP'),
    ('Dilia Alicea', 'Management Support', 'SAP America (Miami)'),
    ('Benjamin Alimi', 'Director', 'Panaya Ltd.'),
    ('Mathieu Allard', 'VP Finance', 'Coveo Solutions Inc.'),
    ('Kristen Allman', 'Sr. Solution Sales Execut…', 'SAP AMERICA, INC.'),
    ('Salazar del Rio Alma Aurora', 'Functional leader', 'Bachoco, S.A. de C.V.'),
    ('Aditya Amar', 'Senior Softw…', 'DOW JONES & COMPANY, INC.'),
    ('Shafaqat Ameez', 'VP Sales - Enterprise Studios', 'Globant, LLC'),
    ('Teja Amerineni', 'Cheif Strategic officer', 'ReleaseOwl'),
    ('David Amiot', 'Managing Director', 'Deloitte'),
    ('Barbi Amodeo', 'Revenue Man…', 'TAMKO Building Products, LLC'),
    ('Anu Anand', 'Chief of Staff', 'SAP INDIA PVT. LTD.'),
    ('Piyush Anandani', 'Direct…', 'Hewlett Packard Enterprise Company'),
    ('Richard Anderson', 'SSE - SCM', 'SAP AMERICA, INC.'),
    ('Tiffany Anderson', 'Manager, SA…', 'Carlisle Construction Materials'),
    ('Joni Angkasa', 'Regional Head of Growth S…', 'SAP ASIA Pte Ltd'),
    ('Sean Antonello', 'VP, SAP Analytics', 'Improving Toronto Inc.'),
    ('Karthik Anupoju', 'Business Data Analyst', 'KATBOTZ LLC'),
    ('Jamie Anushko', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Kohei Aoki', 'Senior Global Account E…', 'SAP Japan Co., Ltd.'),
    ('Ali Aouzal', 'SAP-SCM Consulta…', 'Previan Technologies Inc.'),
    ('Amy Arendt', 'VP, IT Service &…', 'Oldcastle Infrastructure, Inc.'),
    ('Melissa Arin', 'Marketing & Alliances Manager', 'GyanSys, Inc.'),
    ('Akin Aritmac', 'Chief Sales Officer', 'sovanta America Inc.'),
    ('Dhanishtha Arora', 'Consult…', 'Celebal Technologies Americas, Inc.'),
    ('Tanya Arora', 'Global…', 'Celebal Technologies Americas Inc.'),
    ('Chris Arthur', 'Associate Director - Soluti…', 'Collins Aerospace'),
    ('Miguel Artigas', 'CEO', '724BC Consulting SAS'),
    ('Sokrates Aslanidis', 'Territory Account Manager —…', 'Releaseowl Inc'),
    ('Michael Asomaning', 'TECHNICAL LEAD', 'Defense Logistics Agency'),
    ('Da-Wei Au', 'Group Product Manag…', 'Autodesk Asia Pte Ltd'),
    ('Kevin Aubrey', 'Marketing Lead - AMS', 'SecurityBridge GmbH'),
    ('Adib Audi', 'Account Executive', 'SAP Canada'),
    ('Andreas Axer', '', 'WIRTGEN GROUP Branch of John Deere Gmb…'),
    ('Marisol Ayala', 'VP, Corporate…', 'Inspire Medical Systems, Inc.'),
    ('Angel Azat', 'Executive Assistant', 'SAP AMERICA, INC.'),
    ('Deepa B', 'Senior Customer Onboarding Advisor', 'SAP'),
    ('JP BHATT', 'CEO', 'ImpactQA'),
    ('Jin Seon Baek', 'ERP Manager', 'H Mart Companies, Inc.'),
    ('Stefan Baeuerle', 'SVP | Chief Product Officer, SAP HAN…', 'SAP SE'),
    ('Paul Baines', 'Programme Direct…', 'YORK TELECOM LIMITED'),
    ('Staci Baker', 'Director', 'PricewaterhouseCoopers LLP'),
    ('Divya Balaji', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Alvar Baldarrama', 'Procurement Consultant', 'State of Louisiana'),
    ('Christie Balestra', 'Senior Ind…', 'SAP America Inc. (Hudson Yards)'),
    ('Mithun Bangad', 'Sr Manager Finance IT', 'NRG Energy, Inc.'),
    ('Sahil Bansal', 'Senior Manager', 'Tricopp LLC dba CloudPaths'),
    ('Paul Baraniuk', 'Global Solution…', 'Florida Crystals Corporation'),
    ('Horacio Barbosa', 'Proce…', 'Techint Cia Tecnica Internacional SACI'),
    ('Devraj Bardhan', 'SAP AI Leader', 'IBM United Kingdom Limited'),
    ('Paul Barrett', 'Senior Manager, Channel Sa…', 'SPS Commerce'),
    ('Pam Barrowcliffe', 'Product Marketing,…', 'SAP Canada - Waterloo'),
    ('Alejandro Basigalup', 'Jefe de infraestructura corporativo', 'Grupo HZ'),
    ('Martin Bava', 'IT Bus…', 'Techint Cia Tecnica Internacional SACI'),
    ('Lynn Bayer', 'Procurement…', 'Securian Financial Group, Inc.'),
    ('Justin Beachnau', 'Senior Account Exe…', 'Pittsburgh, SAP America'),
    ('Benjamin Beberness', 'Business Architect', 'Proquire LLC'),
    ('Chris Becker', 'Director, Finance Tr…', 'Cintas Corporation No. 1'),
    ('Andy Bell', 'Head of Consulting', 'RESULTING LIMITED'),
    ('Carrie Bennett', 'SVP, Technology Deli…', 'Ascentium Corporation'),
    ('Marissa Bennett', 'Director, Global People Solutio…', 'PepsiCo, Inc'),
    ('James Benson', 'Solutions Sales Executiv…', 'SAP AMERICA, INC.'),
    ('Dan Berard', '', 'International Business Machines Corporation…'),
    ('Ethan Berceli', 'Director of Sales Engineer', 'Mediafly, Inc'),
    ('Frederic Berg', 'VP SAP UI Technologies & Mobile', 'SAP SE'),
    ('Nick Berg', 'SVP Digital Platforms', 'Softserve'),
    ('Elliot Berger', 'Managing Partner, bp', 'SAP UK Limited'),
    ('Kerry Jo Berger', 'Executive Director', 'JPMorgan Chase Bank, NA'),
    ('Catalina Bernal', 'Seller Partner Manager', 'SAP CANADA'),
    ('Kori Betsalel', 'Senior accountant executive', 'SAP CANADA'),
    ('Pallav Bhatnagar', 'Sr. Director', 'LTM'),
    ('Nitin Bhide', 'Regional Sales lead', 'Incture LLC'),
    ('Raja Sekhar Bhomadi', 'Manager/Head of Dept', 'Verizon Sourcing LLC'),
    ('Marco Bickel', 'Vice President IT Program Manage…', 'Bayer AG'),
    ('Amos Biegun', 'CEO', 'Vistex, Inc.'),
    ('Alex Birle', 'Senior Sales Development', 'Confido'),
    ('Justin Bisesi', 'Business A…', 'The Davey Tree Expert Company'),
    ('Ron Blackburn', 'EVP of Sales and GTM', 'CloudPaths'),
    ('Eric Blondin', 'Head of Business Te…', 'SimpleFi Solutions, LLC'),
    ('Matt Blyth', 'Vice President, Global Pr…', 'SAP AMERICA, INC.'),
    ('Sanjeev Bode', 'VP', 'HCL'),
    ('Arndt-Alexander Boehnert', 'Global VP CAS…', 'SAP Deutschland SE &Co.KG'),
    ('Beverley Den Boestert', 'Director - Technology…', 'EY Global Services Ltd'),
    ('Kate Bollard', 'Consulting Manager', 'Collective Insights'),
    ('Raju Bolledla', 'SAP Strategic Advisor', 'SAP Australia Pty Ltd'),
    ('Jackson Borges', 'RVP Finance & Spend', 'SAP International Inc.'),
    ('Patrick Boruta', 'Partner - Business Consultin…', 'Grant Thornton'),
    ('Babs Bouchillon', 'NA Tradeshows and Event Manager', 'Serrala'),
    ('Megan Boulter', 'Director of Strategic…', 'The Silicon Partners Inc'),
    ('Kailen Boumal', 'Sr. Channel Manger', 'ADP, Inc.'),
    ('Art Boyd', 'SVP Growth Partnerships', 'Mirakl'),
    ('Joanne Bradford', 'Procurement Data & Capability Manager', 'JLR'),
    ('Holger Brammer', 'VP AI Ecosystem', 'SAP SE'),
    ('Stephen Brandes', 'VP of Sales', 'Confido'),
    ('Chuck Bratton', 'Vice President of Solutions', 'FPT USA CORP'),
    ('Gary Braunscheidel', 'Chief Technology Offic…', 'Baillie Lumber Co Inc'),
    ('Adam Breiterman', '', 'Maryland & Virginia Milk Producers Cooperati…'),
    ('Oscar Brennan', 'Global Head of Growth for Digital Appli…', 'Atos'),
    ('Renee Brewer', 'Dir Finc Trans.', 'Carrier World Headquarters'),
    ('Tim Brewer', 'Technology Solutions Manager', 'Corevist, Inc.'),
    ('Paul Britter', 'SAP Program Mana…', 'Caterpillar Logistics, Inc.'),
    ('Drew Brooks', 'Chief Development Officer', 'Ergon'),
    ('Jean-F. Brossard', 'Partner & VP Business Development', 'DBC'),
    ('Ian Brown', 'Field Risk Management', 'SAP Canada'),
    ('Jay Brown', '', 'ConsultingNetwork Business Solutions, LLC'),
    ('Jesse Brown', 'Sr Success Executive', 'PartnerTap'),
    ('Michelle Brown', 'Director Supply Chain', 'Raytheon'),
    ('Mitch Brown', 'VP, North America', 'Acuiti Labs'),
    ('Holger Bruchelt', 'Product Manager', 'Microsoft Corporation'),
    ('Eduardo Brunetti', 'Value Advisor', 'SAP Brasil Ltda.'),
    ('Franklin Bruno', 'Solution Advisor Manager -…', 'SAP Brasil Ltda.'),
    ('Renee Bruno', 'IT Manager', 'Prime Conduit, Inc.'),
    ('Ann Bryant', 'Director - Financi…', 'Old Dominion Freight Line'),
    ('Patricia Buchholz', 'Gl…', 'SUSE Software Solutions Germany GmbH'),
    ('Sneha Budhwani', 'Senior Solution Archi…', 'Tricentis Americas, Inc.'),
    ('Phillip Budidharma', 'IS Mana…', 'Charlotte Pipe & Foundry Company'),
    ('Mitchell Burkart', 'Sales Director', 'Globalsource, Inc.'),
    ('Alice Burrell', 'Data Analytics Senior Manager', 'JLR'),
    ('Eamonn Burton', 'TPM', 'SAP'),
    ('Erin Buss', '', 'Globalsource Information Technology III, Inc.'),
    ('Tara Butler-Krgovic', 'VP, NA Experience and E…', 'SAP AMERICA, INC.'),
    ('Shawn Byers', 'VP, Digital Product Marketing', 'SAPinsider'),
    ('YOUNA CHOI', 'Assistant Manager', 'sunjin'),
    ('Juan Carlos Caballero', 'System Developer M…', 'PAN AMERICAN GRAIN'),
    ('Lisa Cabarcos', "America's SAP Allianc…", 'Ernst & Young U.S. LLP'),
    ('Bobby Cain', 'SVP & CIO - North America', 'Schneider Electric'),
    ('Elidan Calvo', 'SAP Manager', 'Align Technology Inc'),
    ('Phil Cameron', 'Growth Officer,…', 'SAP NEW ZEALAND LIMITED'),
    ('Stefan Camp Angell', 'SAP P…', 'Komatsu-Mitsui Maquinarias Perú S.A.'),
    ('Mariano Caniglia', 'Industry Executive Advis…', 'SAP Chile Limitada'),
    ('Amanda Cantu', 'Product Manager', 'Schneider Electric USA, Inc.'),
    ('Seila Carcavilla', 'Innovation Manager', 'JLR'),
    ('Pat Carmody', 'Senior Manag…', 'Sharp Electronics Corporation'),
    ('Tyler Carr', 'Sr. Capabilities Manag…', 'McKinsey & Company'),
    ('Matias Romero Carranza', 'Sales Solution Director', 'Veritas Prime, LLC'),
    ('Sergio Carriero', 'Director', 'Bell Canada'),
    ('Chrissy Caruso', 'Client Engagement Manag…', 'Veritas Prime, LLC'),
    ('Mariana Carvajal', 'Mobile App Lead', 'SAP AMERICA, INC.'),
    ('Gabriele Casalena', 'Director', 'Aubay Italia S.p.A.'),
    ('Sumner Case', 'Sales Director', 'Syntax Systems Limited'),
    ('Margarita Castillo', 'Marketing Director', 'SAP AMERICA, INC.'),
    ('Sam Castro', 'Global Product Marketin…', 'SAP AMERICA, INC.'),
    ('Vy Cates', 'Director, HR PM/Produ…', 'Phillips 66 Company'),
    ('William Cdebaca', 'Group operations Control…', 'Fluor Corporation'),
    ('Donatella Cechet', 'Chief Product Expert — Cloud ERP Fi…', 'SAP SE'),
    ('Ekta Chadha', 'Head of Cloud Delivery,…', 'SAP AMERICA, INC.'),
    ('Joydeep Chakraborty', 'Head of ECS CAA…', 'SAP LABS INDIA PVT. LTD.'),
    ('Arun Chakravarthi', 'Enterprise Account M…', 'Kaar Technologies Inc'),
    ('Kamlesh Chalasani', 'Vice President, Manufacturing', 'Tech Mahindra'),
    ('Greg Chamberland', 'IT, Enterprise…', 'Ocean Spray Cranberries, Inc.'),
    ('Chris Chamberlin', 'Relationship Manager', "Moody's Corporation"),
    ('Prasanna Chand', 'Director - Enterprise Tech', 'Wayfair'),
    ('Srinivasan Chandramohan', 'Manager', 'Cardinal Health Inc.'),
    ('Matt Charleston', 'Sr Manager Fi…', 'Performance Food Group, Inc.'),
    ('Alexandra Charris', 'Business Relationsh…', 'Softtek Renovation SAS'),
    ('Anirban Chatterjee Chatterjee', 'SAP SLED Leader', 'IBM Corporation'),
    ('Karan Chauhan', 'Life Sciences Solutions', 'Cognizant'),
    ('Sanjay Chavan', 'Head Enterpri…', 'Mahindra & Mahindra Limited'),
    ('Abraham Cherian', 'Director Security Govern…', 'Kontoor Brands Inc'),
    ('Venu Cherupillil', 'Systems Engineer Sr Princi…', 'The Home Depot'),
    ('Jeff Cheung', 'SAP Platform Ow…', 'Ionis Pharmaceuticals, Inc.'),
    ('Michelle Chew', 'Sr. Project Coordinator', 'Marine Atlantic Inc.'),
    ('Taiseer Chirakkal', '', 'International Business Machines Corporation…'),
    ('Karen Chirico', 'Executive Director Enterprise Services', 'RTX'),
    ('Will Chisholm', 'Project Manager', 'Southwest Airlines'),
    ('Flora Choi', 'Director, ERP…', 'BioMarin Pharmaceutical, Inc.'),
    ('JongYun Choi', 'Managing Director', 'BSG partners'),
    ('Parinda Choksi', 'CIO - Enablement', 'Ball Horticultural Co.'),
    ('Sanjay Choubey', 'Global Chief Digital an…', 'Sylvamo Corporation'),
    ('Nicolas Christiaen Christiaen', 'CEO', 'Dealside'),
    ('Saurabh Chug', 'Solution Advisor', 'SAP AMERICA, INC.'),
    ('Yoon Chung', 'Solution Engineer Manager', 'Precisely'),
    ('Douglas Ciolli', 'IT Principal Mana…', 'Southern California Edison'),
    ('Tania Cirone-Fenyes', 'Sr. Director Alliances', 'GyanSys, Inc.'),
    ('Odércio Claro', 'CIO', 'Klabin SA'),
    ('Greg Clausing', 'Director SAP COE', 'The Andersons, Inc.'),
    ('Zach Clement', '', 'American Equity Investment Li fe Insurance C…'),
    ('Michael Cobler', 'Sr. Account Executive', 'Cognitus Ltd'),
    ('Tim Coffey', 'Sr. AE', 'SAP AMERICA, INC.'),
    ('Alinne Cogrossi', 'Product Manager, ERP Procure to P…', "Arc'teryx"),
    ('Chad Cohen', 'Client Engagement Manger', 'Veritas Prime, LLC'),
    ('Allan Colaco', 'ERP Transfor…', 'HellermannTyton Corporation'),
    ('Colin Cole', 'IT Director', 'JBS USA Food Company Holdings'),
    ('Clay Coleman', 'Global Service Director, BPO', 'Wipro Limited'),
    ('Andrew Collins', 'SVP ERP Transformation', 'BP'),
    ('Kelli Collins', 'Project Manager', 'BlackJet Marketing'),
    ('Oisin Collins', 'Partner', 'Deloitte'),
    ('Mark Colosimo', 'Director of Strategic Acc…', 'The Silicon Partners'),
    ('Tom Coltrain', 'Enterprise Architect', 'Dominion Energy, Inc.'),
    ('Sean Comer', 'Senior Project…', 'TAMKO Building Products LLC'),
    ('Meena Confait', 'Global Business & Engagem…', 'SAP MENA LLC'),
    ('Alex Connor', 'Senior Develo…', 'Lantech.com Coöperatie U.A.'),
    ('Adam Conrad', 'Bus Proc Architect', 'McKesson'),
    ('Eileen Conway', 'Global Head Strategic Partnerships', 'Qualitest'),
    ('Julie Cooper', 'Client Relationship Executive', 'BravoTECH'),
    ('Michael Coppola', 'VP, Finance & Treasury', 'Ashland Inc.'),
    ('Juan Correa', 'Employee', 'Sharp Corporation'),
    ('Manoel Costa', 'Demo Solutions Expert', 'SAP Brasil Ltda.'),
    ('Sophie-Anne Cote', 'Finance Director', 'Barrette-Chapais'),
    ('Maryanne Coughlin', 'Director', 'PwC'),
    ('Robert Coutu', 'Sr. Accoun…', 'System Design Analysis (SDA) inc.'),
    ('Julie Craig', 'Spon…', 'SPARKS MARKETING (EMEA) LIMITED'),
    ('Bill Cranston', 'SAP Sales Director', 'Techwave'),
    ('Keith Creech', 'Director, Enterprise Sales', 'SPS Commerce, Inc.'),
    ('Philippe Cretier', 'Head Finance and Spend Manage…', 'Santiago'),
    ('Chris Crosby', 'Founder | Managing Partner', 'Adoptlab'),
    ('Ademar Crotti Junior', 'Principal Technical Cons…', 'metaphacts GmbH'),
    ('Ken Crovetti', 'Business Development Manager-…', 'Vertex, Inc.'),
    ('Miguel Cruz', 'Gerente de Calidad', 'Punta Cana'),
    ('Michael Cugliari', 'Senior Account Exec…', 'The Silicon Partners Inc'),
    ('Marco Sanna', '', 'cbs Corporate Business Solutions Unternehm…'),
    ('Rajesh Sarin', 'Global Head - ERP Platf…', 'Analog Devices, Inc.'),
    ('Subhayu Sarkar', '', 'Cognizant Technology Solutions U.S. Corporat…'),
    ('Michael Sass', 'VP, IT', 'Alphatec Holdings, Inc.'),
    ('Yuki Sato', 'Business Consulting…', 'EY Global Services Ltd'),
    ('Naoya Satomi', 'Senior Manager', 'NTT DATA Japan Corporation'),
    ('Klaus-Peter Sauer', 'Product Manager SAP Business Data…', 'SAP SE'),
    ('Vivek Saurabh', 'Director of Business Developm…', 'GyanSys, Inc.'),
    ('Tom Savoie', 'Customer Solution Director', 'EverBlue Partners'),
    ('Andreas Schaefer', 'CRO SCM MEE', 'SAP Deutschland SE &Co.KG'),
    ('James Scheel', 'Solution Sales Executive…', 'SAP AMERICA, INC.'),
    ('Ralf Scherer', 'Global Transfo…', 'SAP Deutschland SE &Co.KG'),
    ('Kathrin Schmalzing', 'Partner', 'PricewaterhouseCoopers LLP'),
    ('Brian Schmidt', 'Principal I.T. Architect', 'Mckesson'),
    ('Jan Schneider', 'GVP Head of AI Partner Ecosystem', 'SAP SE'),
    ('Rebecca Schneider', 'Project Consultant', 'SAP SE'),
    ('Tonia Schneider', 'Principal Accoun…', 'Amazon Web Services, Inc.'),
    ('Pete Scholtens', 'Managing Direc…', 'Delaware North America LLC'),
    ('Axel Schroeder', 'Chief Architect', 'SAP SE'),
    ('Christoph Schroeder', 'Global Head, Industry Business Unit…', 'SAP SE'),
    ('Carsten Schuetz', 'VP, Global He…', 'SAP Deutschland SE & Co.KG'),
    ('Michael Schultz', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Floyd Scott', 'Customer Success Ma…', 'LG CNS America, Inc.'),
    ('Cindy Seaburn', 'S…', 'The School Board of Duval County Florida'),
    ('Kress Sebastian', 'Head of AI, Platforms & Data', 'SAP SE'),
    ('Sandeep Sehgal', 'Vice-President, SAP Services', 'SAP Canada'),
    ('Aparna Seksaria', 'Global Director, Life Sciences IBU', 'SAP'),
    ('Sam Seth', 'GM Retail, Co…', 'On Demand Technologies, Inc.'),
    ('Rahul Sethi', 'Sr. Client Advocate', 'Corevist Inc'),
    ('Kanan Sethi Jawa', 'Director', 'Bombardier Inc.'),
    ('JUAN IGNACIO Sevilla', 'GERENTE DE PRODUCCIÓN', 'plasticaucho'),
    ('Harshal Shah', 'CEO', 'Elsner Technologies pvt ltd'),
    ('Vinay Shah', 'Value Advisor', 'SAP'),
    ('Dawn Shakeshaft', 'Controller', 'Associated Feed & Supply Co.'),
    ('Aditya Shankar', 'Co-fou…', 'Sookti AI Innovations Private Limited'),
    ('Hari Shankar', 'Associate Vice Presi…', 'Hexaware Technologies'),
    ('Murali Shanmugam', 'Business AI Strategy A…', 'SAP Australia Pty Ltd'),
    ('Chris Shano', 'Marketing Head,…', 'ATOS INTERNATIONAL SAS'),
    ('Ashuka Sharma', 'VA', 'SAP America Inc. (Hudson Yards)'),
    ('Dhruv Sharma', 'Assistant Vice Preside…', 'Celebal Technologies'),
    ('Priya Sharma', 'Glo…', 'SNP TRANSFORMATIONS SEA PTE. LTD.'),
    ('Shantanu Sharma', 'Architecture Advisor', 'SAP America (Reston)'),
    ('Suchit Sharma', 'Assistan…', 'Celebal Technologies Americas Inc.'),
    ('Heidi Sheehan', 'Vice President, Information Technol…', ''),
    ('Anastasiya Shemanskaya', 'CFO Customer Office', 'SAP AMERICA, INC.'),
    ('Sameer Shepal', 'Global Lead - SAP…', 'Tata Technologies Limited'),
    ('Colby Sheridan', 'Industry Executive Advis…', 'SAP AMERICA, INC.'),
    ('Scott Sherman', 'SVP Information Te…', 'The Pittsburgh Paints Co.'),
    ('Yasuhiro Shibata', 'Department Manager', 'JSOL Corporation'),
    ('Allon Shiff Shiff', 'Value Advis…', 'SAP Industries (Washington DC)'),
    ('Dong Moon Shin', 'Manager', 'Pan Ocean Co., Ltd.'),
    ('Mary Shinn', 'Managing Director, SAP K…', 'SAP Korea Limited'),
    ('Tomoya Shinozaki', '', 'フォーティエンスコンサルティング株式会社…'),
    ('Nobunori Shiono', 'IT…', '株式会社ベイカレントコンサルティング'),
    ('Krista Shirley', 'Employee', 'Expand Energy Corporation'),
    ('Lisa Shober', 'Mana…', 'Air Products and Chemicals, Inc'),
    ('Olga Shumikhina', 'Umoja HCM Team Lead', 'The United Nations'),
    ('Andrew Sigler', 'Account Director', 'Syntax Systems USA LP'),
    ('Mikolaj Sikorski', 'Strategic Partner Initiatives', 'SAP Ireland Ltd.'),
    ('Jonathan Silva', 'Instituição de Pagament…', 'Nu Pagamentos S.A'),
    ('Renato Silva', 'Solutions Sa…', 'Globant Brasil Consultoria Ltda'),
    ('Sergei Silva', '', 'Vistex'),
    ('Felix Silvagnoli', 'SAP Platform Owner', 'BP International Limited'),
    ('Gianluca Simeone', 'Global SAP CTIO & AI Leader', 'Capgemini'),
    ('Cintia Simonelli', 'Managing Part…', 'SAP Argentina - Buenos Aires'),
    ('Eric Simonson', 'Director - Product Marke…', 'SAP AMERICA, INC.'),
    ('Natalie Singh', 'Global Strategic Scale L…', 'SAP AMERICA, INC.'),
    ('Sukhbir Singh', 'S…', 'The School Board of Duval County Florida'),
    ('Vikrant Sisodia', 'Sr. Product Manager', 'Autodesk, Inc.'),
    ('David Smith', 'VP, Chief Enterprise Ar…', 'SAP America (Reston)'),
    ('Rachel Smith', 'Partner Sales Manager', 'Docusign Inc'),
    ('Mark Smysor', 'Business Systems Analyst in Enterpri…', 'Utilities'),
    ('Delaiah Snowden', 'IT Ana…', 'South Florida Water Management Dist'),
    ('Jairo Soares De Matos', 'Analyst - SAP Busi…', 'Canadian Blood Services'),
    ('Michael Somerville', 'Sales Executive', 'Checkout.com'),
    ('YoonWon Song', 'IT Director', 'i-SENS, Inc.'),
    ('Dag Terje Sorlie', 'Managing Director', 'Accenture'),
    ('Thiago Souza', 'IT CO…', 'MINERACAO SERRAS DO OESTE LTDA'),
    ('Meik Spanowsky', 'Director', 'PricewaterhouseCoopers LLP'),
    ('Thorsten Spihlmann', 'Head of Business Development for T…', 'SAP SE'),
    ('TD Srinivasan', 'Industry…', 'SAP Public Services, Inc. (Hudson Y'),
    ('Mike Stafford', 'Senior ABAP Developer', 'Titan Ventures LLC'),
    ('Jennifer Stapleton', 'VP of Accounting Strategy &…', 'American Equity'),
    ('John Stark', 'Global Head of SAP Alliance', 'Loftware'),
    ('Denis Staudt', '', 'GLOBAL DISTRIBUIÇÃO DE BENS DE CONSU…'),
    ('Maximilian Stein', 'SAP Product Owner - Treasury CPIT', 'SAP SE'),
    ('Amanda Steiner', 'Business Process Architect', 'McKesson'),
    ('Dieter Steinmann', '', 'Fraport AG Frankfurt Airport Services Worldwi…'),
    ('Jorrit Steinz', 'Founder & CEO', 'ChannelEngine.com'),
    ('Robert Stemmler', 'Global Alliances & Ec…', 'McKinsey & Company'),
    ('Yonathan Stephanos', 'SAP Data & AI Business Group Le…', 'Accenture'),
    ('Patrick Stewart', 'Account Executive', 'SAP AMERICA, INC.'),
    ('Jochen Stiebe', 'Head of Sales Treas…', 'Target-Networks GmbH'),
    ('Leslie Stoffel', '', 'CARMEUSE RESEARCH AND TECHNOLOGY S…'),
    ('Miodrag Stojanov', 'Lead Engineer', 'SEMOS SOFTWARE LLC'),
    ('Bojana Stojanovich', 'VP, NA Strategic Partnerships', 'Tricentis'),
    ('Seda Strate', 'Partner Innovation Lead', 'SAP SE'),
    ('Divya Struebing', 'Supply Chain Customer…', 'SAP AMERICA, INC.'),
    ('Kevin Stupp', 'Director S4 Platform', 'The Hershey Company'),
    ('Harish Subramanian', 'Principal Enterprise Arch…', 'SAP AMERICA, INC.'),
    ('Marc Sudjian', 'Enterprise Architect, SAP So…', 'Bombardier Inc.'),
    ('Hirofumi Sugimoto', 'Officer', 'ABeam Systems Ltd.'),
    ('Michael Sukachev', 'Sr. EA', 'Teranet Inc'),
    ('Som Suresh', 'Man…', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('Jain Sushant', 'Chief Revenue Officer, F&S…', 'SAP ASIA Pte Ltd'),
    ('Scott Sutker', 'Vice President Customer Success…', 'Alpharetta'),
    ('Mergenthaler Sven', 'Global Head of Strategic Central Ser…', 'SAP SE'),
    ('Jereme Swoboda', 'Segment Director', 'Avvale, Inc.'),
    ('Debra Syring', 'Senior IT Manager', 'Entegris, Inc.'),
    ('Kai Szatkowski', 'Head of Product Sales', 'Natuvion GmbH'),
    ('MARCO TOMBOLINI', 'Global He…', 'DOLCE & GABBANA BEAUTY SRL'),
    ('KAZUSHI TOYOMASU', 'Global Direct…', 'MOL Chemical Tankers Pte Ltd'),
    ('Stacey Taborelli', 'Executive Business Partn…', 'SAP AMERICA, INC.'),
    ('Ahmed Taher', 'IT Director', 'Al Daajan Trading'),
    ('Chieko Takahata', 'Chief', 'BROTHER INDUSTRIES,LTD.'),
    ('Arai Takahiro', 'Services Delivery Manag…', 'SAP Japan Co., Ltd.'),
    ('Eiji Takashina', 'Associate Director', 'Kyndryl Japan KK'),
    ('Tetsushi Takino', 'Manager', '大和ハウス工業株式会社'),
    ('Makoto Tamura', 'Alliance Group Director', 'FUJITSU LIMITED'),
    ('Chiyuki Tanaka', 'Team leader', 'Recruit Co., Ltd.'),
    ('Steve Tanaka', 'Sr Vice Presid…', 'Blommer Chocolate Company'),
    ('Yasuhiro Tanaka', 'Director', 'Recuruit Co.,Ltd.'),
    ('Kristin Taner', 'Chief Marke…', 'Vortex Software Consulting, LLC'),
    ('Mitchell Tauer', 'Services Account Execut…', 'SAP AMERICA, INC.'),
    ('Roxanna Tavares', 'Director, Gl…', 'The Nielsen Company (US), LLC.'),
    ('Theo Tavrides', 'Vice Presi…', 'NTT Data Business Solutions, Inc.'),
    ('Jamie Taylor', 'Global VP, Strategic Partnerships', 'SAP Canada'),
    ('Meghan Taylor', 'Industry Account Ex…', 'Pittsburgh, SAP America'),
    ('Samantha Taylor', 'Senior Solutions Account Exec…', 'SAP Canada'),
    ('Sarah Taylor', 'Solution Advisor', 'SAP AMERICA, INC.'),
    ('Jorge Tercero', 'Manager/H…', 'Asociacion Mutual Sancor Salud'),
    ('Michael Teti', 'Architect', 'Carlisle Construction Materials'),
    ('Suji Thampi', 'Vice President', 'MINDSPRINT PTE. LTD.'),
    ('Le Thanh Phong', 'Managing Direc…', 'FPT Japan Holdings Co., Ltd.'),
    ('Michael Theis', 'Senior Director, Healthcare Life Scien…', 'Icertis'),
    ('Rene Theriault', 'IT Program Director', 'BRP INC'),
    ('Barbara Thrasher', 'SR STAFF ARCHITECT', 'Tyson Foods, Inc.'),
    ('Nissim Titan', 'CEO', '4CAST SYSTEMS LTD'),
    ('James Tiwari', 'Director', 'Intellioz LLC'),
    ('Shuhei Toba', 'Manager', 'Business Engineering Corporation'),
    ('John Tocci', '', 'Cbs Corporate Business Solutions America In…'),
    ('Oliver Toloui', 'Director - AI…', 'Ibase Operations Corp Qualitest'),
    ('Ray Toma', 'Senior Principal — Global Strategic Initia…', 'ADP'),
    ('Yuko Tominaga', 'Research Writer', 'Freelance'),
    ('Laura Tozzo', 'AI Product Lead SAP IBP', 'SAP SE'),
    ('Eero Traagel', 'Partner', 'IBM Canada Limited'),
    ('Adam Trahan', 'Vice President', 'SAP AMERICA, INC.'),
    ('Evgeny Treskin', 'SAP Alliances Director', 'Argano'),
    ('Chetan Tripathi', 'oCFO Adoption expert', 'SAP'),
    ('Seshagiri Tripurana', 'Senior Director', 'Johnson & Johnson'),
    ('Masaru Tsukahira', 'Director', 'TOKYO ELECTRON LIMITED.'),
    ('Lindsay Tucker', 'Solution Consultant', 'Docusign'),
    ('Paul Turbes', 'Managing Director', 'KPMG LLP'),
    ('Treaver Tyler', 'Tech…', 'Meijer Great Lakes Limited Partnership'),
    ('Kotaro Ueda', 'Chief Operating Officer', 'JSUG'),
    ('Rajkishore Una', 'President/CEO', 'GyanSys, Inc.'),
    ('Bala Parameswara Rao Upadhyay…', 'Associate Director', 'Stefanini, Inc.'),
    ('Oscar Uribe', 'CFO', 'EDUARDONO S A S'),
    ('SACHIN VAIDYA', 'Director - Enterprise Commercial…', 'Pfizer, Inc.'),
    ('Jonathan VON RUEDEN', 'Chief AI Officer', 'SAP SE'),
    ('Wagner Valentin', 'Director of Regulated Indust…', 'SAP Brasil Ltda.'),
    ('Jorge Valles Velásquez', 'KMMP…', 'Komatsu-Mitsui Maquinarias Peru S.A.'),
    ('Henri Vallet', 'VP Sales, Americas B2B', 'Mirakl'),
    ('Jeff Van Pelt', 'Founder / Managing Dire…', 'Javelin Consulting'),
    ('Meredith Van Wyk', 'Americas Field Partner…', 'SAP AMERICA, INC.'),
    ('Joris Van der Donck', 'Sr Manag…', 'Commscope Connectivity Belgium'),
    ('Vijay Varee', 'Senior Manager', 'Petsmart LLC'),
    ('Suman Varma', 'IT Director', 'Cintas Corporation'),
    ('Chris Vassalotti', 'Director', 'Opentext'),
    ('Raju Vedala', 'CEO', 'CES Business Technologies, LLC'),
    ('Asier Vega Sanchez', 'Implementation Consultant', 'Arkyn'),
    ('Jennifer Veillon', 'Dir Project Controls', 'Fluor Corporation'),
    ('Ajay Reddy Velampudi', 'Senior VP - Sa…', 'Miracle Software Systems Inc.'),
    ('William Velastegui', 'JEFE DE TI Y PR…', 'Plasticaucho Industrial S.A.'),
    ('Rajiv Vemula', '', 'Cognizant Technology Solutions U.S. Corporat…'),
    ('Sundu Venkataramani', 'Industry Val…', 'SAP Industries (Washington DC)'),
    ('Venkat Venkataramani', 'VP', 'SAP AMERICA, INC.'),
    ('Tom Venner-Crysell', 'Managing Director', 'ERPeople Solutions Ltd'),
    ('Eduardo Vergara', 'Manager/Head of Dept', 'Agrosuper S.A.'),
    ('Amit Verma', 'RVP, Head of CFO Advisory…', 'SAP ASIA Pte Ltd'),
    ('Kumar Vidit', 'Product Marketing M…', 'SAP America(Bellevue)'),
    ('Lakshmi Vidyashankar', 'VP of IT', 'Marvin Engineering Co., Inc.'),
    ('Jayant Vikram', 'Cloud Delivery Lead', 'Accenture LLP'),
    ('Yeni Villanueva', 'Supervisora…', 'Compañia Minera Antamina S.A.'),
    ('Robert Vinyard', 'VP and Senior Partner', 'IBM'),
    ('Thomas Vioux', 'Partner', 'PwC'),
    ('Anil Visal', 'Partner', 'PricewaterhouseCoopers LLP'),
    ('Clara Viscido', 'Consulting Services Director', 'GEONOSIS'),
    ('Paulo Vita Vita', '', 'Get Servicos de Gestao, Tecnologia e Particip…'),
    ('Ranjan Vitt', 'AI Compliance Governance Program…', 'SAP SE'),
    ('Jose Voisin', 'Global CIO', 'Carmeuse'),
    ('Christina Volk', 'Head of Strate…', 'SAP Deutschland SE &Co.KG'),
    ('Jessica Voyles', 'Account Executive, South', 'SAP AMERICA, INC.'),
    ('Sandeep Vyas', 'Solutio…', 'Incture Technologies Private Limited'),
    ('Thomas von Alm', 'SVP Cross-Solution Services', 'SAP SE'),
    ('Markus von Quast', 'Global Head Industry Ecosystem', 'SAP SE'),
    ('TATSUO WATANABE', 'Principal Cons…', 'D I SQUARE CORPORATION.'),
    ('Masayuki Wada', 'SVP, Head of Corporate Digit…', 'Fujitsu Limited'),
    ('Stephen Wagenheim', 'Senior Sales Executive - Suppl…', 'Dallas (Allen)'),
    ('Neha Wahi', 'Global Alliance Lead', 'A.T. Kearney, Inc.'),
    ('Waka Wakabayashi', 'Associate Partner', 'KPMG Consulting Co., Ltd.'),
    ('Gustavo Waldfogiel', 'LAC HCM Head', 'SAP Argentina - Buenos Aires'),
    ('Shashikant Walimbe', 'Vice President & Global Head -…', 'LTM LIMITED'),
    ('Julie Walker', 'Sr. Director, Enterprise Applicatio…', 'Armstrong'),
    ('Rob Wallace', 'Senior Manager Digital & In…', 'Jaguarlandrover'),
    ('Enzhou Wang', 'Chief Technology Officer', 'City of Tacoma'),
    ('May Wang', 'Direc…', 'Deloitte Consulting (Shanghai) Co., Ltd.'),
    ('Adam Warner', 'Cost Analyst', 'Marathon Cheese Corporation'),
    ('Kosuke Watanabe', 'Senior Account Executive', 'SAP Japan Co., Ltd.'),
    ('Takashi Watanabe', '執行役員', 'JFE Systems,Inc.'),
    ('Robert Watson', 'Sr Account Executive', 'SAP AMERICA, INC.'),
    ('Ashley Waxman', 'Strategic Sales Executive', 'Aevitas IT LLC'),
    ('Christy Weaver', 'Global Demand Generation Man…', 'Vertex, Inc.'),
    ('Mike Weaver', 'Senior I…', 'True Commerce Inc. TrueCommerce'),
    ('Chris Webster', 'SVP IT Strategy & Architecture', 'Ahold Delhaize'),
    ('Matt Webster', 'Director of…', 'Gardner White Furniture Co., Inc.'),
    ('Patrick Weil', 'IT Director', 'Metrie Canada Ltd'),
    ('Sarah Weiler', 'Manager, Busine…', 'Ball Horticultural Company'),
    ('Adam Werner', 'VP, Corporate Technology', 'Crocs, Inc.'),
    ('Maddie Werner', 'Director of Delivery Solutions', 'Robra IT'),
    ('Katherine West', 'CX Account Executive', 'SAP Canada'),
    ('Anja Wettling', 'Managing Director', 'anuwo GmbH'),
    ('Charleen Wetzstein', 'SAP Principal Architect', 'PROSPECTOR, LLC'),
    ('Peter Wheatley', 'Enterprise Architect…', 'SAP America (Houston)'),
    ('Robb White', '', 'BSN SPORTS, LLC f/k/n Sports Supply Group,…'),
    ('Peter Widmer', 'Chief of Staff to the Global Head of S…', 'SAP SE'),
    ('Chad Wiech', 'Director of Solution…', 'Pittsburgh, SAP America'),
    ('Chamnida Wijetilleke', 'Managing Director', 'The Ducats Group LLC'),
    ('Pete Wilkins', 'NA Partner Manager', 'SAP America(Bellevue)'),
    ('Mark Willey', 'Vice…', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('Ed Williamson', 'Client Services Lead', 'XMATERIA LTD'),
    ('Monica Willis', 'HR Strategy and Value A…', 'Plano- Legacy West'),
    ('Charlotte Wilson', 'Senior Manager Strategic Cha…', 'Direct Energy'),
    ('Emily Wisemiller', 'Sr. Data Analyst', 'Molex'),
    ('Julia Wolfe', 'Analyst Relations Manager', 'IBM'),
    ('Jennifer Workman', 'Techn…', 'Universal Destinations & Experiences'),
    ('Steven Wright Wright', 'VP Sales', 'Acuiti Labs Limited'),
    ('Monty Wurth', 'VP of Operations', 'Optima Consulting L.L.C.'),
    ('Brad Wylie', 'Account Executive', 'SAP Canada'),
    ('KAORI YASHIKI', 'Business Resear…', 'Hitachi Digital Services LLC'),
    ('YOUNGHO YOO', 'Team Leader', 'LG CNS Co., Ltd.'),
    ('Mohamed YUSUF', 'Head of Integrated Toolchain', 'SAP MENA LLC'),
    ('Hikaru Yafuso', 'Senior Alliance Director', 'Databricks'),
    ('Sonoko Yamamoto', 'Partner Business Manager', 'SAP Japan Co., Ltd.'),
    ('Osamu Yamazaki', 'Co…', 'Hitachi Industry & Control Solutions, Ltd.'),
    ('Kenji Yanagi', 'Group Leader', 'ASAHI GROUP JAPAN, LTD.'),
    ('EJ Yang', 'IT Deputy Director', 'MediaTek Inc.'),
    ('Kiran Yarlagadda Yarlagadda', 'Managing…', 'Adroix Corp DBA CodeForce 360'),
    ('Takayuki Yasuda', 'sales', 'JFE Systems, Inc.'),
    ('Tomoki Yasuda', 'AssistantMana…', 'NTT DATA Japan Corporation'),
    ('Kazuhiro Yonekawa', 'Chief/Proj…', 'CANON MARKETING JAPAN INC.,'),
    ('Sungeui Yoon', 'Senior Specialist', 'Microsoft'),
    ('Christopher Yope', 'SAP Supply C…', 'DXC Technology Services LLC'),
    ('Kohei Yoshimatsu', 'Manager', 'アズビル株式会社'),
    ('taichi yoshida', 'Senior Ma…', 'BENIC SOLUTION CORPORATION'),
    ('nakajima yuki', 'Member', 'Nitori Co., Ltd.'),
    ('Stefan Zach', 'VP Global IT', 'Wieland Group'),
    ('Beau Zaremski', 'VP of Sales', 'SAP AMERICA, INC.'),
    ('Yuan Zhang', 'Senior Project Manager, SAP AI RIG', 'SAP SE'),
    ('Cathy Zhou', 'IT Director, EBS', 'Ecolab Inc.'),
    ('Gustavo Zintak', 'Manager/Head of Dept', 'SWISS MEDICAL S.A.'),
    ('Alina Zuberi', 'Global Content Strategist', 'SAP MENA LLC'),
    ('Yoshiaki Agata 縣', 'consultant', 'AJS株式会社'),
    ('裕紀 阿保', 'Manager', 'FORTIENCE CONSULTING INC.'),
    ('謙介 青木', 'Manager, Uvance Market Developme…', 'Fujitsu'),
    ('James Rasque', 'IT Business Analyst Supervisor', 'Kwik Trip Inc'),
    ('Abhishek Rastogi', 'Lead Specialist, Business Cont...', 'National Grid'),
    ('Jeannine Rau', 'SCSM', 'SAP AMERICA, INC.'),
    ('Koushika Ravikumar', 'Business Analyst', 'KATBOTZ LLC'),
    ('Prachi Ray', 'Marketing - SAP', 'Tech Mahindra Limited'),
    ('Vasee Rayan', 'Senior Vic...', 'SAP Labs, LLC. (Newtown Square)'),
    ('Carlos Recio', 'Vice President Testing Practice', 'Innovise IT'),
    ('Araja Reddy', 'Managing Director', 'Deloitte Consulting'),
    ('Sasi Reddy', 'Sr. SAP Applicati...', 'Sun Chemical Corporation'),
    ('Nico Reichen', '', 'PricewaterhouseCoopers GmbH Wirtschaftsp...'),
    ('Caitlin Reidy', '', 'Icertis Inc.'),
    ('Kristen Reinken', 'Journey & Change Management L...', 'Accenture'),
    ('Efrain Reyes', 'SAP Function...', 'Aecon Construction Group Inc.'),
    ('Luis Reyes', 'Regional Sales Director SSLATAM', 'Vistex Inc.'),
    ('Dan Rhoadhouse', 'Process Ar...', 'The Scotts Miracle-Gro Company'),
    ('Fernando Riccardi', 'Chief Operating Officer', 'Exed Consulting'),
    ('Devin Rich', 'Chief Info. Off.', 'Lansing Building Products, LLC'),
    ('Trey Riley', 'Senior Director', 'Leprino Foods Company'),
    ('Lisa Rinaldi', 'Finance Lead, ED...', 'General Electric Company'),
    ('Angela Rios', 'CIO', 'Centro de Sistemas y Negocios S.A.'),
    ('Jerome Robertson', 'Director, AI Driven Business Insights', 'Pfizer'),
    ('Lauren Robinson', '', 'Sparks'),
    ('Devin Robnick', 'Head of NA Field Market...', 'SAP AMERICA, INC.'),
    ('Virginia Roda', 'Chief Technology Off', 'Southbay S.R.L.'),
    ('Alexander Rodde', 'Head of Corporate Portfolio', 'SAP SE'),
    ('Sebastian Rode', 'Global ERP Delivery Lead', 'Roche'),
    ('Hernan Rodriguez', 'Practice Manager', 'Nearshore Argentina S.A.'),
    ('Josiane Roger', '', 'CGI Information Systems and Management C...'),
    ('Laurie Rogosheske', 'Director E...', 'Wolters Kluwer United States Inc.'),
    ('Rachel Romanoski', 'Director - SAP SCM...', 'SAP America (Houston)'),
    ('Diana Romaya', 'SAP...', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('John Rooney', 'Regional Partner Director', 'Stonebranch'),
    ('Susanne Ross', 'Senior Partner Marketin...', 'Coveo Solutions Inc.'),
    ('Cori Rothgery', 'Data & A...', 'DURACELL U.S. OPERATIONS, INC.'),
    ('Sylvain Roy', 'It Director', 'Heroux-Devtek'),
    ('Renee Rubino', 'Senior Manager of Alliance Partnershi...', 'SMC3'),
    ('Felix Rubio', 'Industry Advisor Latin America', 'SAP Colombia'),
    ('Frank Ruetten', 'Client Partner', 'IBM Deutschland GmbH'),
    ('Frank Ruland', '', 'PricewaterhouseCoopers GmbH Wirtschaftsp...'),
    ('Roxanne Ryan', 'Director, Executive Progr...', 'SAP AMERICA, INC.'),
    ('Scott Ryerson', 'Partner Executive', 'Capgemini America, Inc.'),
    ('Royce Ryu', 'Head of Services Deliver...', 'SAP Japan Co., Ltd.'),
    ('Natalie Röthel', 'Executive Assistant', 'McKinsey & Company'),
    ('mariano rivarola', 'Gerente Industrial Regional', 'HZ GROUP S.R.L.'),
    ('Hanumantha Rao Sabbireddy', 'New Business', 'Tech Mahindra'),
    ('Andrew Sackett', 'Director of Partnerships', 'Collibra Belgium BV'),
    ('Rinchen Sahni', 'Digital Marketing Manager', 'KATBOTZ LLC'),
    ('KG Saito', 'Vice President', 'MACNICA, INC.'),
    ('Makoto Saito', 'IT Development Dept', 'Tokyo Electron Limited'),
    ('Tito Salazar', 'Partner Growth Manager', 'OneRail'),
    ('Sarah Salzman', 'Regional VP of Sales', 'Basware, Inc.'),
    ('Julissa Samuels', 'Gerente de aplica...', 'American Sportswear, S.A.'),
    ('Brent Sandberg', 'Project Manager, Business Transf...', 'Carmeuse'),
    ('Sachin Sangle', 'VP', 'ImpactQA'),
    ('KATSUYUKI SHINZEKI', 'Assistant Manager', 'Marubeni Corporation'),
    ('JASBIR SINGH', 'Associate Partner, Global...', 'IBM India Pvt Ltd'),
    ('Mayur Patel', 'Director IT COE', 'Axalta Coating Systems, LLC'),
    ('Subhajit Paul', 'IT Technical Lead - SAP CoE', 'Jabil Circuit, Inc.'),
    ('Dan Pavlick', 'Director of Strategic Partnerships', 'OneRail'),
    ('Matt Pegoraro', 'Field Marketing Manager', 'SAP AMERICA, INC.'),
    ('Paul Pelletier', 'Logistics Operatio...', 'Defense Logistics Agency'),
    ('Leila Penteado', 'Value Advisor Head Brazil', 'SAP Brasil Ltda.'),
    ('Rogério Peres', 'CIO', 'JBS USA'),
    ('Eddie Perez', 'Master Producti...', 'Marvin Engineering Co., Inc.'),
    ('Fernanda Perez', 'General Manag...', 'SAP Argentina - Buenos Aires'),
    ('April Perkins', 'Sr. Mgr. SAP...', 'thyssenkrupp Materials NA, Inc'),
    ('Ernie Perno', 'St Account...', 'The Hackett Group- Answerthink'),
    ('Teresa Perrius', 'Director, Payroll Operations', 'American Airlines'),
    ('Catherine Perry-Robertson', 'Partner, Natio...', 'PricewaterhouseCoopers LLP'),
    ('Hari S. Peruri', 'CIO', 'AGCO Corp'),
    ('George Peter', 'Sr Mgmt Business Sys', 'Pure Storage Inc.'),
    ('Mark Petersen', 'Sr...', 'Advanced Workforce Inc DBA TotalTek Inc'),
    ('Sladjana Petrovic', 'Architect', 'IGM Financial'),
    ('Jim Phelan', 'EVP, US Country M...', 'msg global solutions, Inc.'),
    ('Matt Phillips', 'Sr. Director', 'Woodward Inc'),
    ('Alex Pierroutsakos', 'Industry Exec Advisor -...', 'SAP America (Miami)'),
    ('Dave Pinet', 'Finance AE', 'SAP Canada - Ottawa'),
    ('James Pinto', '', 'International Business Machines Corporation'),
    ('Peter Pluim', 'President, Global Cloud Op...', 'SAP UK Limited'),
    ('Tomas Pluma', 'SCM Solution Advisory LAC', 'SAP Mexico'),
    ('Chris Podeszwa', 'Principal Accoun...', 'Alokai (ex - Vue Storefront)'),
    ('Franck Poisson', 'Partner', 'PWC US Group LLP'),
    ('Eric Pokriefka', 'Manager, Customer IT', 'DTE Energy'),
    ('Michael Polaha', 'SR VP Record to Report', 'BlackLine'),
    ('Paula Popity', 'Celco -...', 'Celulosa Arauco y Constitucion S.A.'),
    ('Simone Porcu', 'Partner', 'IBM'),
    ('Karin Porwoll', 'Global Strategic Partner Marketing SAP', 'IBM'),
    ('Raja Pothapragada', 'Customer/Partner Success Man...', 'Panaya, Inc.'),
    ('Joel Pousinho', 'Managing Partner', 'Maxfield Group Inc'),
    ('Andrea Powers', 'Global Account Director', 'Mediafly'),
    ('Stacy Price', 'IT Manager', 'American Airlines, Inc.'),
    ('Whitney Price', 'Director Supply Chain C...', 'SAP AMERICA, INC.'),
    ('Brenda Prinzing', 'Senior Co...', 'SAP America Inc. (Hudson Yards)'),
    ('Pascal Proulx', 'Business Analyst', 'STI Maintenance inc'),
    ('Mark Pryor', 'VP Digital, M&A+ERP', 'bp'),
    ('Manoj Purohit', 'SVP and Head of APAC Cor...', 'SAP ASIA Pte Ltd'),
    ('Joyce Purtell', 'Vice President, Tax Tech...', 'Johnson & Johnson'),
    ('Angie Pyles', 'HCM Account Executive', 'Plano- Legacy West'),
    ('Ashley Quinn', 'Solution Architect', 'Gentex Corporation'),
    ('Huzefa Qutbuddin', 'Executive Vice President', 'Royal Cyber Inc.'),
    ('MANOJ KUMAR RAMALINGAM', 'Senior Manager', 'CSL BEHRING LLC'),
    ('AMIT RANJAN', 'Sr. Director IT Enterprise Applicat...', 'Saputo Inc'),
    ('Budi Rachman', 'Predictive...', 'Hamilton Prime International LLC'),
    ('Arun Rajakani', 'Architect - SAP Cloud', 'A.O. Smith Corporation'),
    ('Vishal Rajpal', 'VP Client Inn...', 'Sutherland Global Services Inc'),
    ('Kannan Ramanathan', 'Director of Sales', 'SoftServe, Inc.'),
    ('Rajesh Ramegowda Shankarappa', 'IT', 'Honeywell International Inc'),
    ('Claudia Ramos', 'Sales representative', '724 BC Consulting SAS'),
    ('Warren Rampersaud', 'Enterprise Account E...', 'Amazon Web Services'),
    ('Liam Ranik', 'Industry Account Executi...', 'SAP AMERICA, INC.'),
    ('Paul Rascoe', 'Janitor', 'Beam Therapeutics'),
    ('Kazuto Nakada', 'Territory Ecosystem Man...', 'SAP Japan Co., Ltd.'),
    ('Yoshihiro Nakamura', 'Chief Info. Off.', 'MAFTEC Co., Ltd.'),
    ('KiWoong Nam', 'CTO', 'Blueward inc.'),
    ('Balachander Nandagopal', 'Senior Director', 'Icertis, Inc.'),
    ('Travis Nault', 'Manager', 'AscendN, LLC'),
    ('DEBS Nayak', 'Director — SAP...', 'INNOVAPTE CORPORATION'),
    ('Madhur Nayak', 'AI Architect', 'Miracle Software Systems Inc.'),
    ('Sunny Neely', 'Industry Advisor, Consu...', 'SAP AMERICA, INC.'),
    ('Daniel Nersveen', 'PFERD-W...', 'August Rüggeberg GmbH & Co. KG'),
    ('MJ Nevarez', 'Planner/Scheduler', 'Pantexas Deterrence LLC'),
    ('Pamela Newberry', 'Manager S4 Systems', 'Collins Aerospace'),
    ('Albert Nguyen', 'VP Strategic Growth', 'Qualitest'),
    ('Tom Nierlich', 'VP, Strategic Alliances', 'Sovos'),
    ('Youssef Nifaoui', 'Customer Success Mana...', 'SAP AMERICA, INC.'),
    ('Jim Nissen', 'Senior Program Manager', 'Caterpillar Inc.'),
    ('Steve Noffke', 'Architect', 'American National Insurance'),
    ('Dongjin Noh', 'Senior Professional', 'Samsung Electronics'),
    ('Pavel Nouel', 'Vice President,...', 'Colgate-Palmolive Company'),
    ('Carlos Nunez', 'MDR', 'Vendelux'),
    ('matthew nasta', 'IT OTC Manager', 'S.C. Johnson & Son, Inc.'),
    ("Liz O'Neill", 'Director, Business Deve...', 'DIBELL GROUP, INC.'),
    ("Conor O'Rourke", 'SAP Account Manager', 'ALKU'),
    ('Atilola Odeyemi Odeyemi', 'Associate VP', 'Africa Finance Corporation'),
    ('Halil Oezcelik', 'Customer Officer', 'SAP SE'),
    ('Masayoshi Okita', 'Engineer', 'Hitachi, Ltd.'),
    ('Testuo Okuma', 'Executive Partner', 'BAYCURRENT, INC.'),
    ('Hiroshi Okura', 'SAP Japan CFO', 'SAP Japan Co., Ltd.'),
    ('Yuta Okuyama', 'IT person', 'NTTデータグループ'),
    ('Matt Olive', 'Vice President of Sales', 'T S P'),
    ('Aleksandro Oliveira', 'Chief Financial Officer', 'Grupo Edson Queiroz'),
    ('Cristian Olsen', 'Chief Info. Off.', 'Grupo Herman Zupan'),
    ('Andre Ory', 'OTS ERP Director', 'State of Louisiana'),
    ('Rauf Osho', 'Senior SAP System E...', 'MIT Lincoln Laboratory'),
    ('Catherine Ouellet', 'Team Leader SAP Busine...', 'Foliot Furniture Inc.'),
    ('Tatsuya Owada', '', 'NIPPON STEEL Hitachi Systems Solutions, Inc.'),
    ('Chad Owen', 'Principal, Customer Success', 'msg Global'),
    ('Christine Owens', 'Sr PM/ S/4HANA lead', 'e.l.f. Cosmetics, Inc.'),
    ('Megha Oza', 'Strategi...', 'Splisys IT Consulting Private Limited'),
    ('HyunMo PARK', 'CEO', 'BizTech i Co., Ltd.'),
    ('Carlos Mauricio Pacheco Campan...', 'Regional BRM', 'Softtek'),
    ('Sachin Pai', 'SVP & Global Head —...', 'Celebal Technologies'),
    ('Shieun Paik', 'Director IT', 'Cardinal Health 200, Inc.'),
    ('Ganesh Palanievelu', 'Vice President', 'Tech Mahindra'),
    ('Augusto Palma', 'Executive Manager CoE SAP', 'HYPERA S.A.'),
    ('Rodolfo Pampin', 'Director', 'BAITCON S.A.'),
    ('Joyce Pan', 'Finance Manager', 'SAP (China) Co., Ltd.'),
    ('Debasis Panda', 'Delivery Director', 'Defense Logistics Agency'),
    ('Carolina Paolini', 'Business Readiness...', 'Jaguar Land Rover Ltd'),
    ('Ravikiran Papthimar Papthimar', 'Sr. Dire...', 'Incture Technologies Private Limited'),
    ('Keshav Parameshwara', 'Senior Customer...', 'SAP LABS INDIA PVT. LTD.'),
    ('Fernando Pariani', 'Chief In...', 'CENTRO MEDICO AMENABAR S.R.L.'),
    ('Adarsh Parikh', 'CEO', 'Silver Touch Technologies Canada Ltd.'),
    ('Edward Park', 'Agent 008', 'National Amusements, Inc.'),
    ('Sang-Yull Park', 'Team Leader', 'Woongjin Co., Ltd.'),
    ('Anfernee Parker', 'Senior Account Executive', 'SAP AMERICA, INC.'),
    ('Brian Partlow', 'Assis...', 'Medical College of Virginia Foundation'),
    ('Jenny McLean', 'Partner, Retail Industry...', 'Clarkston Consulting'),
    ('Kathryn McLean McLean', 'Director', 'BONFIRE CONSULTING LIMITED'),
    ('Tommy McMullen', 'SAP Practice Lead', 'Fidelis Companies LLC'),
    ('John McNally', 'Senior Account Executive', 'SAP AMERICA, INC.'),
    ('Tom McSorley', 'General Ma...', 'The Gill Corporation --Maryland'),
    ('Mark Meanwell', 'Senior Manager Data & Analytics', 'Sylvamo'),
    ('Michael Meany', 'Enterprise Account Exec...', 'SAP AMERICA, INC.'),
    ('Shane Meehan', 'Sr. Director', 'BioMarin Pharmaceutical, Inc.'),
    ('Thomas Mehlkopf', 'Head of Treasury and Working Capit...', 'SAP SE'),
    ('Nilay Mehta', 'Principal Solution Archit...', 'SAP AMERICA, INC.'),
    ('Mariana Melbardis', '', 'Price Waterhouse & Co Asesores de Empresa...'),
    ('Emily Meltzer', 'Developme...', 'Accenture Federal Services LLC'),
    ('Ritesh Menon', 'Senior Vice President & Business...', 'Incture LLC'),
    ('Janet Mercado', 'Power & Cloud Client Leader', 'IBM'),
    ('Katherine Merrick', 'Supv IT Program M...', 'Puget Sound Energy, Inc.'),
    ('Monica Alejandra Mesa', 'Team Lead SAP Projec', 'Cementos Argos S.A.'),
    ('Ryan Mezzanotte', 'SAP Account Manager', 'Alku, LLC'),
    ('Maya Midmore', 'Industry Account Executive', 'SAP Canada'),
    ('Lynn Mikoshi', 'Account Executive', 'SAP Japan Co., Ltd.'),
    ('Joe Miles', 'Life Sciences Industry Director', 'UI Path'),
    ('Patrick Miller', 'Director - Enterprise Applicat...', 'Cerapedics Inc'),
    ('Rebecca Miller', 'Acc. Operations Mgr.', 'Purdue University'),
    ('Piyush Mistry', 'Partner', 'Deloitte'),
    ('Rich Mitton', 'IT Director', 'Mathis Home'),
    ('S Mohanavelu Mohanavelu', 'ERP solu...', 'Gulfstream Aerospace Corporation'),
    ('Sanjeev Monga', 'Director', 'Kraft Heinz Foods Company'),
    ('Matt Monroe', 'Sr. Services Account...', 'SAP America (Houston)'),
    ('Hyunsook Moon', 'DIRECTOR', 'BSG partners'),
    ('Brian Moore', 'SVP & General Manager, Servic...', 'SAP Canada'),
    ('Stephine Morbach', '', 'American Equity Investment Life Insurance C...'),
    ('Dodjie Morelos', 'Director', 'Carlisle Construction Materials'),
    ('Abby Morgan', 'Customer Engagement Manag...', 'Visionsoft Inc.'),
    ('Lori Morgan', 'VP, Sales', 'SAP AMERICA, INC.'),
    ('Ritsuo Moriya', 'SAP AMO', 'Kobelco Systems Corp.'),
    ('Alex Moronta', 'Gerente Soluciones...', 'Pasteurizadora Rica S.A.'),
    ('Meir Morozov', 'Enterprise Account Specialist', 'Panaya, Inc.'),
    ('Craig Moskowitz', 'SAP Program Director', 'Empower'),
    ('Michael Moukeiber', 'Senior Director', 'Molex, LLC'),
    ('Basant Mudgal', 'Consultant, Business...', 'Celebal Technologies'),
    ('Krish Mujje', 'SVP, Digital & AI S...', 'Tachyon Technologies LLC'),
    ('Maximilian Mundel', 'VP Platform Sales', 'Adyen'),
    ('Hanane Murakami', 'Consultant', 'IBM Japan, Ltd.'),
    ('Kentaro Murata', 'Empl...', 'パナソニックインダストリー株式会社'),
    ('Wataru Murayama', 'Sales Manager(Retail /...)', 'SAP Japan Co., Ltd.'),
    ('Kylie Murphy', 'Mar...', 'SAP Global Marketing(Newtown Square)'),
    ('Craig Murray', 'Business Transformation...', 'SAP AMERICA, INC.'),
    ('Piramanayagam Muthusamy', 'Global Head, SAP Te...', 'Tech Mahindra Limited'),
    ('Kishore Muthyala', 'Sales', 'Miracle Software Systems Inc.'),
    ('Jay Myers', 'Value Advisor', 'Ariba Inc.'),
    ('Suzi Myers', 'Director, Application Dev', 'Cardinal Health'),
    ('Florian Müller', 'Head of Security Product Manageme...', 'SAP SE'),
    ('PRAKASH NARAYANAN', 'Enterprise Account Executive', 'Bristlecone, Inc.'),
    ('Suresh NG', 'SAP Sales Specialist', 'Tech Mahindra Limited'),
    ('Wanda NI LAIGHIN', 'Vice President, Global Marketing...', 'SAP France'),
    ('Kota Nagashio', 'Man...', 'パナソニック インダストリー株式会社'),
    ('Masaki Nagata', 'Consulting Divisi...', 'DI SQUARE CORPORATION'),
    ('Sahiba Nagpaul', 'AVP, SolEx & Partner Success at I...', 'Icertis, Inc.'),
    ('Anand Lokineni', 'IT Architect', 'Jabil Circuit, Inc.'),
    ('Sergio Lopez', 'CFO', 'WINES AND SPIRITS S.A.'),
    ('Diego Loria', 'Gerente de sistemas', 'MAINCAL S.A.'),
    ('Nathalie Lotra', '', 'Eli Lilly and Company Lilly Technology Center...'),
    ('Tammy Louie', 'Senior Financial Systems Analyst', 'AutoZone'),
    ('Wepoint Louis', 'Vice-President', 'ONEPOINT'),
    ('Lydia Lousky', 'Supply Ch...', 'SAP America Inc. (Hudson Yards)'),
    ('Diego Lozano', 'MD', 'Seidor Consulting SA'),
    ('Jeroen Luijrink', 'Account Executive', 'SAP Nederland BV'),
    ('Michael Lukac', 'Enterprise AE', 'Pittsburgh, SAP America'),
    ('Adam Benjamin Lustig', 'VP, Solution Advisory', 'Basware'),
    ('Bill Lynch', 'Sr Director IT', 'Sharp'),
    ('Thomas Lynch', 'VP, Value Advisory', 'SAP AMERICA, INC.'),
    ('Nicolas Löwe', 'Partner', 'BearingPoint GmbH'),
    ('Ravish M', 'Expert, Advanced Success Pl...', 'SAP MENA LLC'),
    ('YOSHIHIRO MISAWA', 'Managing Director General...', 'JFE Systems,Inc.'),
    ('TIZIANA MOROSINI', 'Corporate Marketing Events', 'SAP Italia S.p.A.'),
    ('Santipriya Madabushi', 'President', 'Sapta Global Inc.'),
    ('Sanjay Madala', 'SAP Competency...', 'ShimentoX Technologies'),
    ('Janet Maddern', 'ERP Program Manager', 'UT-Battelle LLC'),
    ('Aaron Maestas', 'Sr Director, Health Systems Natio...', 'McKesson'),
    ('Sergo Maglakelidze', 'Director, Privat...', 'SAP Deutschland SE &Co.KG'),
    ('Evan Magouirk', 'Manager, Pricing & A...', 'McKesson Corporation'),
    ('Souvik Majumdar', 'CTO', 'Acuiti Labs Limited'),
    ('Naresh Makhijani Makhijani', 'Glo...', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('Bob Marchand', 'COO', 'Innovise-IT'),
    ('Melissa Marchetti', 'SAP...', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('John Marcine', 'Industry Account Executive', 'SAP Canada'),
    ('Alan Martin', 'Senior Solutions Sales E...', 'SAP AMERICA, INC.'),
    ('Lawrence Martin', 'Chief Product Officer an...', 'SAP AMERICA, INC.'),
    ('Sascha Martin', 'SVP, Global H...', 'SAP Deutschland SE & Co.KG'),
    ('Martine Martine', 'Controller', 'Portefeuille Soucy Inc'),
    ('Raphael Martins', 'Sol...', 'Seidor - Tecnologia da Informação LTDA.'),
    ('Fernando Martins Salles', 'I...', 'AMBAR SERVICOS DE INFORMATICA LTDA.'),
    ('Takahiro Marufuji', 'Dire...', 'MITSUBISHI CHEMICAL CORPORATION'),
    ('Shiho Maruta', 'Team leader', '（株）リクルート'),
    ('Adriana Masson', 'CTO', 'Chicken Farmers of Ontario'),
    ('Tsuyoshi Masuda', 'VP and Head of RISE Ja...', 'SAP Japan Co., Ltd.'),
    ('Monika Matel-Sousa', 'Deputy Chief Technology Offi...', 'City of Toronto'),
    ('Deepak Mathur', 'Architect', 'Medline Industries, LP'),
    ('Nikhil Mathur', 'Senior Director', 'Celebal Technologies'),
    ('Doug Maulbetsch', 'Director SAP applications', 'Lucid Motors'),
    ('Jared Mayers', 'Acquisition Suppo...', 'Pantexas Deterrence LLC'),
    ('Lia Mazmanian', 'Marketing Execution Specialist', 'SAP'),
    ('Nelia Mazula', 'Supply Chain Sales Exec...', 'SAP AMERICA, INC.'),
    ('Gerard McCann', 'Strategic Allianc...', 'Opentext Ot Addison Office'),
    ('Kevin McCollom', 'Global VP, General Mgr.', 'Archlynk, LLC'),
    ('Gerry McCool', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Michaelene McCormick', 'Senior Services Account...', 'SAP AMERICA, INC.'),
    ('Lauren McCullin', 'Senior Sales Executive-...', 'SAP AMERICA, INC.'),
    ('John McDonnell', 'Industry Advisor, Wholes...', 'SAP AMERICA, INC.'),
    ('Teresa McGivern', 'Global Workforce Tranf...', 'PROFINDA LIMITED'),
    ('Ben McGrail', 'Managing director', 'XMATERIA LTD'),
    ('Denise McGuigan', 'Part...', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('Patricia McKinley', '', 'CARMEUSE RESEARCH AND TECHNOLOGY S...'),
    ('Jan Krueger', 'Technical Account Director', 'Intel Corporation'),
    ('Mike Krug', 'SAP Technical...', 'Pennsylvania State University'),
    ('Siddhi Kshatriya', 'Organizational Change Managem...', 'AutoZone'),
    ('Greg Kull', 'Leader, SAP Partner Sales', 'Vertex, Inc.'),
    ('Amit Kumar', 'SAP Pro...', 'Molex Electronic Technologies, LLC.'),
    ('Sandeep Kumar', 'Partner [Data, Analytics & AI]', 'SCMXpert'),
    ('Jazz Kundra', 'Project Manager', 'Amgen Inc.'),
    ('Sabrina Kunze', 'Consulting Sen...', 'SAP Deutschland SE &Co.KG'),
    ('Trent Kurbis', 'Manager, IT Service M...', 'The Mosaic Company'),
    ('Makoto Kurimoto', '', 'キヤノンマーケティングジャパン株式会社'),
    ('Dennis Kurlandski', 'Managing Director', 'KPMG'),
    ('Kohei Kuroda', 'Senior Consultant', 'Fortience Consulting Inc.'),
    ('Amir Kviatkovsky Kviatkovsky', 'CFO', 'Panaya Ltd.'),
    ('Changhyeok Kwon', 'Senior Professional', 'Samsung Electronics'),
    ('Christina Kyriasoglou', 'Tech Reporter', 'Bloomberg LP'),
    ('Martin Kögel', 'CEO', 'VOQUZ Labs'),
    ('Arvind LAKSHMAN', 'IT Director', 'BioMerieux Inc.'),
    ('JUNG HYUN LIM', 'Group leader', 'Blueward INC.'),
    ('Kun-Yi LIM', 'Principal Tax Product...', 'Autodesk Asia Pte Ltd'),
    ('ROBSON LUIS DA CUNHA', 'Product Director', 'Invent Software Ltda.'),
    ('Jonathan La Blunda', 'Gerente Comercial Interpac...', 'INTERPACK S.A.'),
    ('Marc Laberge', 'SCM Solution Director', 'DBC'),
    ('Rosemary Lafferty', 'Business Excellence...', 'Americas Styrenics LLC'),
    ('Brian Laird', 'Exec...', 'SAP America Public Sec.(Newtown Sq)'),
    ('Nick Lake', 'Digital and Innovation Manager - Logistics', 'JLR'),
    ('Vijay Lakhanpal', 'AVP - CLOUD I...', 'Celebal Technologies Pvt Ltd.'),
    ('Jose Luis Lanchas', 'Global Events', 'SAP'),
    ('Nicholas Landolfi', 'Customer Success Partner', 'Ariba Inc.'),
    ('Mark Landrosh', 'Industry Executive Advis...', 'SAP AMERICA, INC.'),
    ('Joanne Lang', 'CEO', 'Natuvion Americas, Inc.'),
    ('Marcus Lange', 'Global Partner Manager for S...', 'Dynatrace LLC'),
    ('Juan Carlos Lara', 'KMMP...', 'Komatsu-Mitsui Maquinarias Peru S.A.'),
    ('Joseph Lattanzi', 'Logistics Business Analyst', 'Lincoln Laboratory'),
    ('Sean Laughlin', 'Product Marketing Direct...', 'SAP AMERICA, INC.'),
    ('George Lawrie', 'Senior Dir...', 'SAP Industries (Newtown Square)'),
    ('Julian Lebowitz', 'Director SAP and Busines...', 'Centerra Gold Inc.'),
    ('Austin Ledesma', 'Account Director', 'Solace'),
    ('DaeWon Lee', 'Marketing', 'Blueward inc.'),
    ('Hye Jin Lee', 'Consultant', 'Woongjin Co., Ltd.'),
    ('Jang Moo Lee', 'System Engineer', 'LG CNS America Inc'),
    ('Juhong Lee', 'Account Executive', 'SAP Korea Limited'),
    ('Steven Leighton', 'Head Digital & Inn...', 'Standard Chartered Bank'),
    ('Dan Lemashov', 'Sr. Finance SSE', 'SAP AMERICA, INC.'),
    ('Bobbi Lemoshov', 'Data Analyst', 'IMS Trading'),
    ('Dave Leong', 'Principle - High Tech Strategic Ac...', 'Bristlecone'),
    ('David Leslie', 'Software Engineer in Test', 'FlightSafety'),
    ('Brent Lewis', 'Sr. Mgr. Data...', 'Armstrong World Industries, Inc.'),
    ('Kelly Lewis', 'Director SAP Ap...', 'Brown-Forman Corporation'),
    ('Verena Leymann', 'Vice President and Head of Corporat...', 'SAP SE'),
    ('Al Limaye', 'VP', 'LSInextGen'),
    ('Mara Lincoln', 'Sr Sponsorship Engagement Direct...', 'Freeman'),
    ('Robert Lindberg', 'Director of Ent. Sys', 'CHS Inc.'),
    ('Angela Lipscomb', 'IT Manager', 'DTE Electric Company'),
    ('Andrew Little', 'Director', 'Canadian Blood Services'),
    ('Noelia Llobera', 'Sales Director', 'Sasami'),
    ('Gwyneth Lloyd-Jones', 'Technology', 'Accenture Japan Ltd.'),
    ('Kirk Logan', 'VP Supply Chain, C...', 'Pittsburgh, SAP America'),
    ('Maruti Kampli', 'Director - API Digital Integrations', 'Miraclesoft'),
    ('Hideaki Kanamori', 'Principal Project Manager', 'SAP'),
    ('Masaya Kanatani', 'Project M...', 'BENIC SOLUTION CORPORATION'),
    ('Sandeep Kandirelli', 'Director', 'Tachyon Technologies LLC'),
    ('Nadine Kanja', 'Global Head Industry Business Unit...', 'SAP SE'),
    ('Saumya Kapoor', 'Global Head of Sales, Planni...', 'SAP UK Limited'),
    ('Kiran Kumar Karanam', 'IT SAP', 'FlightSafety International Inc.'),
    ('Eswar Karnam', 'ERP Associate Director', 'Stefanini'),
    ('Srinivas Karnati', 'Director, Digital Tr...', 'Tachyon Technologies LLC'),
    ('Srinu Karuturi', 'SCSM-Procurement', 'New York - Hudson Yards'),
    ('Mariusz Karwowski', 'SAP Architect', 'SLAVIA CONSULTING LTD'),
    ('Vivek Kasera', 'Associate Vice President', 'Birlasoft'),
    ('Sean Kask', 'Chief AI Strategy Officer', 'SAP (Schweiz) AG'),
    ('Sasi Kathirasen Mani', 'SENIOR VICE PRESIDE...', 'SAP Australia Pty Ltd'),
    ('Chaz Kattamuri', 'Client Partner', 'TSP'),
    ('Tony Kavadas', 'Chief Sales Officer', 'Mediafly'),
    ('JR Kavanagh', 'Sr Account Exec - SCM', 'SAP AMERICA, INC.'),
    ('Masayoshi Kawase', 'AssistantMana...', 'NTT DATA Japan Corporation'),
    ('Kentaro Kazama', 'SectionManager', 'JSOL Corporation'),
    ('Cristina Kazda', 'Director of IT, Commercial', 'Ecolab Inc.'),
    ('Steve Kelchen', 'Sr Account Executive', 'TotalTek'),
    ('Sean Kelly', 'President', 'BlackJet Marketing'),
    ('Sarah Kennedy', 'VP, SAP Services', 'SAP Canada'),
    ('Aisling Keogh', 'Marketing Manager', 'Coveo Solutions Inc'),
    ('Shigeki Keumi', 'BU Head, General Manager', 'Hitachi Asia'),
    ('George Kezhakekuttiyil', 'SBU Leader', 'Cognizant'),
    ('Darshana Khadke', 'SAP Business Analyst', 'KNPC Holdco, LLC'),
    ('Junghyun Kim', 'Senior Director', 'Samsung Electronics Co., Ltd.'),
    ('Ron King', 'VP, Sales Executive', 'Deloitte Consulting LLP'),
    ('Kaede Kitabatake', 'Sales', 'Kyndryl Japan KK'),
    ('Hiroshi Kitano', 'Partner', 'EY Strategy and Consulting Co., Ltd.'),
    ('Adam Kiwon', 'Managing Director', 'whitepaper.id GmbH'),
    ('Jason Klimas', 'Functional An...', 'Hellermanntyton Corporation'),
    ('Jonathon Kline', 'EBS Deputy Portfo...', 'Defense Logistics Agency'),
    ('Edward Kloczkowski', 'Director of Information Te...', "Paul's Corporation"),
    ('Candice Knauss', '', 'American Equity Investment Life Insurance C...'),
    ('Motoki Kobashi', 'Director, PFC sales3', 'SAP Japan Co., Ltd.'),
    ('Faith Koch', 'HR Coordi...', 'Basin Electric Power Cooperative'),
    ('Gerard Koelmeyer', 'Customer References', 'SAP Japan Co., Ltd.'),
    ('Christian Koestler', 'Global Director, Client...', 'McKinsey & Company'),
    ('Hiroki Komine', '営業', 'JFE Systems,Inc.'),
    ('Hiroki Komiyama', 'Gen...', 'NTT DATA Global Solutions Corporation'),
    ('Srikanth Kondagunta', 'Information Systems Offi...', 'The United Nations'),
    ('Brian Kooistra', 'Facilities Syste...', 'Exact Sciences Corporation'),
    ('Chris Kornely', 'Solutions Engineer', 'Aflac, Incorporated'),
    ('Chris Kosrow', 'VP of Sales', 'Donna'),
    ('Mykola Kosyak', 'SAP Techn...', 'System Design Analysis (SDA) inc.'),
    ('Kotani Kotani', 'General Manager', 'BROTHER INDUSTRIES,LTD.'),
    ('Matt Kramer', 'VP, Supply Chain Manag...', 'SAP AMERICA, INC.'),
    ('Filip Kransfeld', 'Practice Director', 'Avvale Inc'),
    ('Stephan Kreipl', 'Head of Product Management SAP I...', 'SAP SE'),
    ('Joel Kremke', 'SVP, WW Partner Alliances & Progr...', 'OpenText'),
    ('Jens Kreuter', 'Executive Communic...', 'zeit:raum digital GmbH'),
    ('Libby Krider', 'Sales Executive', 'TrueCommerce'),
    ('Gopal Krishnan', '', 'INK IT Solutions and Consulting Private Limite...'),
    ('Pam Jeffries', '', 'Cognizant Technology Solutions U.S. Corporat...'),
    ('Sergey Jermakov', 'Senior Partner', 'SIA Clarity Labs'),
    ('Jessica Jestis', 'Technology Manager', 'Southwest Airlines Co.'),
    ('Rajat Jetly', 'VP - Sales and BD', 'INNOVISE IT LLC'),
    ('Mithlesh Jha', 'Managing p...', 'Noshtek Consulting Corporation'),
    ('Jim Thomas Jim', '', 'Wietersdorfer Finanz und Beteiligungs GmbH...'),
    ('Jurema Johnson', 'Business Development', 'ReleaseOwl'),
    ('Vijay Johnwesley', 'Sr Mgr SAP Delivery', 'Leprino Foods Company'),
    ('Brian Jones', 'Services Partner Manager', 'SAP AMERICA, INC.'),
    ('Darius Jones', 'Senior Value Advisor', 'SAP AMERICA, INC.'),
    ('Sony Jose', 'IT', 'FlightSafety International Inc.'),
    ('Sunny Joshi', 'Regional Sales Leader', 'Veritas Prime, LLC'),
    ('Aaron Joy Joy', 'Business Consultant', 'Travis County, TX'),
    ('Kenneth Juengling', 'Manager...', 'Pennsylvania Turnpike Commission'),
    ('Christian Jäkel', 'VP', 'Schwarz Digits'),
    ('GYOYEON KIM', 'Team Manager', 'Blueward INC.'),
    ('Kimikazu Kabata', 'Solution Advisor Expert', 'SAP Japan Co., Ltd.'),
    ('Jeremy Kahl', 'Procureme...', 'Los Alamos National Laboratory'),
    ('Yogi Kalra', 'CEO', 'INNOVAPTE CORPORATION'),
    ('Armin Kaltenmeier', 'Partner, Global Chief...', 'Ernst & Young U.S. LLP'),
    ('Dishank Kamath', 'Program Manager', 'Apple Inc.'),
    ('Ravi Kishore Kamma', 'Principal Produc...', 'ReleaseOwl Private Limited'),
    ('Susan Cunningham', 'Senior Programmer / An...', 'Unisys Corporation'),
    ('Anindya Gaine', 'Program Director SAP Imp...', 'Fluor Corporation'),
    ('Suresh Gali', 'IT Solutions Architect', 'NRG Energy, Inc.'),
    ('Francisco Galindo', 'Sr Director IT finance', 'Colgate Palmolive'),
    ('George Galindo', 'Account Director', 'SAP Industries, Inc.'),
    ('Glenn Gammon', 'Director of S...', 'TLP Management Services LLC'),
    ('Joanne Gammon', 'Partner Delivery Manager', 'Ariba US Inc.'),
    ('Suman Gandhe', 'FICO Consultant', 'Siemens Energy'),
    ('Gary Gang', 'Client Engagement Manag...', 'Veritas Prime, LLC'),
    ('Javier Garcia', 'Commercial Dir...', 'Smartshift Technologies, Inc.'),
    ('Jose Garcia', 'Sr. Director, SAP Practice Lead', 'Nsight, Inc.'),
    ('Amit Garussi', 'VP Product', 'Panaya Ltd.'),
    ('Patti Gary', 'Senior Enterprise Architect', 'Tyson Foods, Inc.'),
    ('Dino Gattola', 'Senior Account Executive, Sup...', 'SAP CANADA'),
    ('Boris Gebhardt', 'Manager...', 'STARTEAM Global Germany GmbH'),
    ('Frank Genevieve', 'SAP Sales Executive', 'NTT DATA Inc.'),
    ('Brent George', 'SAP Advisor', 'Tricentis GmbH'),
    ('Jacob George', 'Director', 'Raytheon'),
    ('Mark George', 'Program Direct...', 'Delaware North America LLC'),
    ('Eliza Georgescu', 'Senior Manager, Partner...', 'Collibra Belgium BV'),
    ('Kimberly Gershenzon', 'Finance Account Executi...', 'SAP AMERICA, INC.'),
    ('Deana Gervais', 'Strategic Sales Support Specialist', 'Pferd Inc.'),
    ('Stefanie Geßler', 'SAP EWM Expert', '4flow SE'),
    ('Keya Gholap', 'Full Stack Developer', 'KATBOTZ LLC'),
    ('Benedikt Gieger', 'Strategic Projects, SAP SCM', 'SAP SE'),
    ('Richard Gilbert', 'Head of B2B Partner...', 'Worldpay (UK) Limited'),
    ('Stacey Gilbert', 'Director', 'Merck'),
    ('Don Gillespie', 'Senior Director Strategic Alliances', 'ADP, Inc.'),
    ('Joe Golemba', 'Global Head, Strategic Alliances...', 'Vistex, Inc.'),
    ('Raul Gomez', 'VP of IT', 'Hexagon AB'),
    ('Santiago Julian Gomez', 'Supply Chain Regional Man...', 'INTERPACK S.A.'),
    ('Moises Gonzalez', 'Client Engagement Manag...', 'Veritas Prime, LLC'),
    ('Oziel Gonzalez', 'VA Head Mexico', 'SAP Mexico'),
    ('Nelson González', 'Subgerente e Operaciones...', 'Grupo Kaufmann'),
    ('Senthil Gopalan', 'D-1 (SVP)', 'The United Nations'),
    ('Pooven Govender', 'APAC CLOUD ARCHITE...', 'SAP Australia Pty Ltd'),
    ('Christine Graham', 'Chief Information Officer', 'Lakeview Farms, LLC'),
    ('Geoff Gray', 'Head of Product', 'The Config Team'),
    ('Andrew Greaves', 'Sen...', 'SAPOCOM Technologies Private Limited'),
    ('Samuel Grenade', '', 'Coveo Solutions Inc'),
    ('Betsy Griffin', 'Senior Account Executive', 'SAP AMERICA, INC.'),
    ('Paula Griffin', 'Seni...', 'Medical College of Virginia Foundation'),
    ('Nicole Griffith', 'Sr. Director, SAP Alliance', 'Protera'),
    ('Tim Grochowski', 'Senior Cloud Executive', 'SAP AMERICA, INC.'),
    ('Anette Grossmueller', 'Head of Cross Product Management,...', 'SAP SE'),
    ('Scott Groth', 'Directir, ERP Architect', 'Pfizer, Inc.'),
    ('John Grzybek', 'Senior SAP Projec...', 'Fujitsu North America, Inc.'),
    ('Rodolfo Guerrero', 'Account Manager', 'GBM Dominicana'),
    ('Alex Guglielmetti', 'VP - IT Advisor', 'Pantexan Deterrence'),
    ('Patricia Guillermo', 'It Lead', 'Kellanova/Mars'),
    ('Dmitri Guinzbourg', 'Team Lead/Supervisor', 'Air Canada'),
    ('Timothy Guizon', 'Finance Manager', 'Henry Company LLC'),
    ('Sriram Hariharasubramanian', 'Partner, Tech Consult...', 'EY Global Services Ltd'),
    ('Lori Harner', 'Global Vice President, Pr...', 'SAP AMERICA, INC.'),
    ('Melissa Harris', 'IT Program Manager', 'Masco Corporation'),
    ('Paul Harris', 'Senior Director, SAP Basi...', 'Varsity Brands, LLC.'),
    ('Joe Hartnett', 'Sales Director', 'OpenText'),
    ('Richard Hatton', 'VP Platform Engin...', 'NBCUniversal Media, LLC'),
    ('Kishie Hattori', 'Chief Partner Officer', 'SAP Japan Co., Ltd.'),
    ('Chelsea Hebb', 'Director, Cons...', 'Collective Insights Consulting'),
    ('Heiko Hecht', 'President', 'IBIS America Inc.'),
    ('Tess Heiligers', 'Business Advisor to SVP ERP Tranfo...', 'BP P.L.C.'),
    ('Christian Heinrich', 'Chief Solutions Officer & Membe...', 'sovanta AG'),
    ('Isabel Heinz', 'Sales Consultant', 'anuwo GmbH'),
    ('David Heitz', 'Account Director', 'SAP'),
    ('Nicolas Helmstaetter', 'Treasury Expert', 'SAP SE'),
    ('Frauke Hering', 'Sovereign Cloud Portfolio Manager', 'SAP SE'),
    ('Adriana Hernandez', 'Head Architecture', 'Bachoco, S.A. de C.V.'),
    ('Sergio Hernandez', 'Head of IT Solutions Ma...', 'SAP AMERICA, INC.'),
    ('Valarie Hernandez', 'Business Analyst', 'Travis County, TX'),
    ('Juan Manuel Hernandez Bello', 'GERENTE SERVICI...', 'Organizacion Terpel S.A.'),
    ('Ralph Hess', 'Executive...', 'Navigator Business Solutions, Inc.'),
    ('Chris Hilko', 'Industry Account Executi...', 'SAP AMERICA, INC.'),
    ('Scott Hillhouse', 'Industry Account Executi...', 'SAP AMERICA, INC.'),
    ('Brandon Hilton', 'Enterprise Syst...', 'Eastman Chemical Company'),
    ('Kent Hinkemeyer', '', 'Wolters Kluwer Global Business Services B.V.'),
    ('Gary Hinton', 'Managing Partner - Shell', 'SAP Nederland BV'),
    ('David Hoag', 'Sr. Manager IT SAP', 'Builders Firstsource, Inc'),
    ('Stefan Hoffmann', 'Vice President Strategy & Soluti...', 'Argano LLC.'),
    ('Robert Holland', 'Chief Re...', 'Wellesley Information Services, LLC'),
    ('Michael Hom', 'Global Head of Digit...', 'Jpmorgan Chase & Co.'),
    ('Ricardo Honda', 'Head of BTM Brazil', 'SAP Brasil Ltda.'),
    ('Keith Hontz', 'Global Head of SAP Alliance', 'Zscaler, Inc.'),
    ('Stuart Hooker', '', 'Shell Information Technology International B.V.'),
    ('Norma Hopkins', 'SLED Field Marketin...', 'SAP Canada - Waterloo'),
    ('Jeffrey Hornibrook', 'Managing Partner', 'SAP AMERICA, INC.'),
    ('Erin Houston Houston', 'IT Solution Manager', 'MSA the Safety Company'),
    ('Aaron Hovick', 'Asst. Director', 'Hy-Vee, Inc.'),
    ('Mike Howard', 'Managing Director', 'Thinklogicx'),
    ('Hector Hoz', 'VP Solution Advisory Spend...', 'SAP Brasil Ltda.'),
    ('Haibo Huang', 'Senior Director', 'SAP AMERICA, INC.'),
    ('Holina Huang', 'Head of CE&A of CS&D...', 'SAP Taiwan Co., Ltd.'),
    ('Yvania Huertas Vargas', 'Manager/Head o...', 'Banco de Crédito del Perú'),
    ('Josh Hulme', 'VP of Sales', 'INSPYR Solutions, LLC'),
    ('Jens Hungershausen', 'Chairman of the Board', 'DSAG eV'),
    ('Ryan Hurney', 'Sr. Manager', 'DXC Technology Services LLC'),
    ('Farheen Hussain', 'Solution - Customer Suc...', 'SAP AMERICA, INC.'),
    ('Omar Hussein Olmedo', 'Poject Manager', 'Bachoco, S.A. de C.V.'),
    ('Jared Hyde', 'VP / Assistant GM, Project Phoenix', 'CRH'),
    ('KAZUSHI INA', 'Manager', 'JFE Systems,Inc.'),
    ('Manabu Ichinogo', 'Senior Principal', 'Open Text K.K.'),
    ('TOSHIKATSU Ikeuchi', 'General...', 'NEC Networks & System Integration'),
    ('Masakazu Imanaga', 'Head of Process Industr...', 'SAP Japan Co., Ltd.'),
    ('Vincent Immordino', 'Director, Private Equity & Canada Sales', 'Esker'),
    ('Akari Inada', 'Employee', 'ABeam Systems Ltd.'),
    ('Tatsuya Inagaki', 'General Manager', 'Sony Global Solutions Inc.'),
    ('Al Ingallinera Jr', 'VP, Product Management...', 'Baton Simulations'),
    ('Babu Inti', 'CIO', 'CommScope, Inc. of North Carolina'),
    ('Rick Isom', 'Enterprise Architect', 'SAP AMERICA, INC.'),
    ('Ken Ito', 'Division Manager', 'TIS Inc.'),
    ('Morgan Jacob', 'Director Enterprise', 'L B Foster Company'),
    ('Amith Kumar Jada', 'SAP Progr...', 'Tata Consultancy Services Limited'),
    ('Mahi Jadhav', 'QTC Transformation Man...', 'Acuiti Labs Limited'),
    ('Chung JaePhil', 'Sales Manager', 'SAP Korea Limited'),
    ('Andrew Jaehnig', 'SAP Manager', 'ALKU'),
    ('Alon Jaffe', 'VP Fe...', 'SAP America Public Sec.(Washington)'),
    ('Anand Jain Jain', 'MD - Enterprise Technolo...', 'Eisner and Amper'),
    ('Mehga Jain', 'Enterprise Architect - M...', 'SAP INDIA PVT. LTD.'),
    ('Naren Jain', 'Managing Dire...', 'PricewaterhouseCoopers LLP'),
    ('Prateek Jain', 'Lead Consultant', 'Celebal Technologies'),
    ('Soumyaa Jain', 'Content Specialist', 'Cognitus Consulting LLC'),
    ('Raj Jakhete', 'Vice President, I...', 'Oliver Healthcare Packaging'),
    ('William Jan', 'Senior Value Advisor', 'SAP AMERICA, INC.'),
    ('Nathan Janardhana', 'Information Systems Offi...', 'The United Nations'),
    ('Lars Janitz', 'Senior Exe...', 'NTT DATA Business Solutions AG'),
    ('Brian Janzen', 'SVP, Continuous Impr...', 'Graham Construction'),
    ('Jose Antonio Jaramillo', 'Gerente', 'Pyramid Consulting SAS'),
    ('Pawel Jaroszewicz', 'Senior Solutions Engineer', 'Onapsis Inc'),
    ('Suneth Jayawardhane', 'Senior Principal, Valu...', 'SAP America (Reston)'),
    ('VALERIAN HARRIS', 'Vice President', 'HCL America Solutions Inc.'),
    ('Angie Halderman', 'Vice President, Sales', 'Deloitte'),
    ('Sarah Haley-Fuentes', 'Director of Solution Engineering', 'Vistex Inc.'),
    ('Callie Hall', '', 'SAP Global Marketing'),
    ('Deborah Hamilton', 'Head of Global Marketing', 'Bristlecone, Inc.'),
    ('Joe Hamilton', 'Sr. Director AME Mfg. Technology', 'Honeywell'),
    ('Sean Hamlin', 'Value Advisor', 'SAP AMERICA, INC.'),
    ('Youngshin Han', 'IT Team Manager', 'i-SENS. Inc'),
    ('Rebecca Hanna', 'Head of Services, ANZ', 'SAP AUSTRALIA'),
    ('Manoj Harbhajanka', 'CEO', 'Acuiti Labs Limited'),
    ('Hadi Hares', 'Global Lead Product Manager', 'SAP SE'),
    ('Ajay Gupta', 'Mana…', 'Reliance Comfort Limited Partnership'),
    ('Anupam Gupta Gupta', 'President', 'Celebal Technologies Americas, Inc.'),
    ('Niladri Gupta', 'Managing Director', 'Deloitte Consulting LLP'),
    ('Piyush Gupta', 'Global Head -…', 'Celebal Technologies Pvt Ltd.'),
    ('Raj Gupta', 'Managing Director', 'Intellioz LLC'),
    ('Varun Gupta', '', 'American Water Works Service Company, Inc.…'),
    ('Vishal Gupta', 'Head of Finance & Spe…', 'SAP Australia Pty Ltd'),
    ('David Gust', 'Account Executive', 'SAP AMERICA, INC.'),
    ('Nestor Guzman', 'Dire…', 'Aerovias Del Continente Americano S.A.'),
    ('Kalman Gyula', '', 'BSN SPORTS, LLC f/k/n Sports Supply Group,…'),
    ('Karthik Gobi gobimayilsamygound…', 'Service Owner (…', 'Honeywell International Inc'),
    ('Gordon Folz', 'Account Executive', 'Bristlecone, Inc.'),
    ('Sandra Liliana Forero Cifuentes', 'SAP Product Manag…', 'Softtek Renovation SAS'),
    ('Nina Forlenza', 'Team Lead, Senior HRBP', 'ADP, Inc.'),
    ('Chris Foti', 'Director, ISV Alliances', 'Basware Oyj'),
    ('Jeff Foy', 'Vice President, Supply C…', 'SAP AMERICA, INC.'),
    ('Luciana Franquet', 'Project Manager', 'Galicia Seguros S.A.U.'),
    ('Andreas Franz', 'He…', 'Heraeus Consulting & IT Solutions GmbH'),
    ('Tom Frederick', 'Senior Director', 'GlobalSource IT'),
    ('Alan Freedman', 'VP Sales - Central…', 'The Addmore Group Inc.'),
    ('Jeremy Freeman', 'Director, Technology', 'Aritzia'),
    ('Brian Freymann', 'Director, SAP Strategic Acco…', 'Bristlecone, Inc.'),
    ('Patrick Friday', 'CEO', 'Alokai'),
    ('Lionel Fridman', 'VP SCM MCLAC', 'SAP Argentina - Buenos Aires'),
    ('Joakim Frisberg', 'Managing Director', 'Accenture'),
    ('Oliver Froehlich', 'SAP Partner Manager Europe', 'Vertex, Inc.'),
    ('Takeshi Fukushima', 'General Manager', '大和ハウス工業株式会社'),
    ('Sean Furukawa', 'Deputy CEO', 'BearingPoint NA LLC'),
    ('Satyanarayana Gade', 'Enterprise Archi…', 'Simpson Strong-Tie Co., Inc.'),
    ('NISHANT GAUTAM', 'CEO', 'www.innovise-it.com'),
    ('SANJAY KUMAR GUPTA', 'VICE PRESIDENT', 'Tech Mahindra Limited'),
    ('Jennifer Ertler', 'Principal', 'Deloitte'),
    ('Jose Esparza', 'Director…', 'BFS Ingenieria Aplicada S.A. de C.V.'),
    ('Jose Manuel Estevz Estevez', 'Technology Consulta…', 'EY Global Services Ltd'),
    ('Brandon Evans', 'Managing Dire…', 'PricewaterhouseCoopers LLP'),
    ('SHIGEHIRO FUJIKI', 'Chief Info…', 'Mitsubishi Corporation (Americas)'),
    ('SATOSHI FUJITA', 'Partner', 'EY Global Services Ltd'),
    ('Luciano Fanti Bianco', 'Managing Director', 'Accenture'),
    ('Kimberly Farino', 'IT Project Manager', 'MIT Lincoln Laboratory'),
    ('John Farr', 'Value Advis…', 'SAP Industries (Washington DC)'),
    ('Jonathan Farrell', 'Enterprise Account Executive', 'Panaya'),
    ('Tim Faubert', 'Executive Director,…', 'BeiGene (Beijing) Co., Ltd'),
    ('Angelo Fazio', 'Global Sales', 'IBM Corporation'),
    ('Beth Feaster', 'Sr Business Develop…', 'INSPYR Solutions, LLC'),
    ('Craig Fee', 'Sr. Business A…', 'Purdue University Global, Inc.'),
    ('Richard Ferling', 'Sourcing ma…', 'The Pittsburgh Paints Company'),
    ('Alejandro Ferreira', 'CEO', 'Bintech, S.A. de C.V.'),
    ('Jeff Fillegar', 'Sr Director Solution Engineering', 'Tricentis'),
    ('Rich Filler', 'Sr. Mgr IT', 'Exelon Corporation'),
    ('Colin Finley', 'Partner', 'Kearney & Company, P.C.'),
    ('JP Finnell', 'Senior Director Strategic…', 'SAP AMERICA, INC.'),
    ('Jack Fiorini', 'Senior Business Development…', 'Onapsis Inc.'),
    ('Kurt Fischbach', 'Director of Data Governa…', 'ScottsMiracle-Gro'),
    ('Cedric Fiske', 'Sales Development Representative', 'Coveo'),
    ('Kieran Fitzgerald', 'Software Sales Lead', 'The Config Team Ltd'),
    ('Susana Flores Cabrera', 'Contracts Coordinator', 'Cheney Bros, Inc.'),
    ('Bonnie Davies', 'VP Finance & Spend', 'SAP Canada'),
    ('Wendy Davis', 'Solution Customer S…', 'SAP America (Houston)'),
    ('Rebecca Day', 'IS ERP and Revenu…', 'The Health and Hospital'),
    ('Andrea De Colle', 'Enterprise Arc…', 'SAP Argentina - Buenos Aires'),
    ('Jeff DeHulsters', 'Business Consultant', 'Travis County, TX'),
    ('Adrian DeSantis', 'Sales Engineer', 'TrueCommerce'),
    ('Sushil Debare', 'ECS Regional Delivery H…', 'SAP AMERICA, INC.'),
    ('Larry Deille', 'Senior Manager Digital Transf…', 'Lam Research'),
    ('Drew Delaney', 'Business P…', 'The Scotts Miracle-Gro Company'),
    ('Amy Delise', 'Director', 'Walgreens'),
    ('Meghan Demo', 'Director of Marketing', 'Cognitus Consulting LLC'),
    ('James Dender', 'Account Director', 'SAP AMERICA, INC.'),
    ('Sven Denecken', 'SVP SAP Industries', 'SAP SE'),
    ('Urnav Desai', 'Prin…', 'Deloitte Touche Tohmatsu Services, LLC'),
    ('Alan Detlif', 'Director Business Sys…', 'The Crosby Group LLC'),
    ('Holly Devine', 'Industry Advisor', 'SAP AMERICA, INC.'),
    ('Andrea Devroy Devroy', 'Senior Dire…', 'PT Intermediate Holdings III,  LLC'),
    ('Raman Dhooria', 'Vice President', 'Celebal Technologies Pvt Ltd.'),
    ('Aboubacar Diallo', 'AI Governance Program Co-Lead', 'SAP SE'),
    ('Sofia Diaz', 'SR. Manager Inside Sales', 'Globant'),
    ('Kathrin Dorothea Diederich', '', 'KPMG AG Wirtschaftsprüfungsgesellschaft -…'),
    ('Linda Dietzel', 'Director, IT Supply C…', 'The Hershey Company'),
    ('Guillermina Digregorio', 'Global Head of GCO Private Clo…', 'SAP Mexico'),
    ('Ralf Dillmann', 'Partner & C…', 'BearingPoint North America LLC'),
    ('Michael Dillon', 'Global Platform Leader', 'IBM Corporation'),
    ('Haricharan Dingari', 'Enterprise Arc…', "Bob's Discount Furniture, LLC"),
    ('Everett Dittman', 'Strategic Customer Advisor, A…', 'Databricks Inc.'),
    ('Pankaj Diwan', 'Senior Director', 'ArchLynk, LLC.'),
    ('Ralph Dommes', 'CEO', 'Dommes Consulting, Inc.'),
    ('Mari Doroud', 'HRIS Manager', 'Nucor'),
    ('Amisha Doshi', 'Industry Account Executi…', 'SAP AMERICA, INC.'),
    ('Rakesh Doshi', 'Architecture Advisor', 'SAP AMERICA, INC.'),
    ('Chris Dougherty', 'Senior Director', 'Pfizer, Inc.'),
    ('Ryan Doyle', 'Principal Co…', 'SAP Industries (Washington DC)'),
    ('Adam Drent', 'Director', 'GlobalSource IT'),
    ('Shannon Drost', 'Vice President Technology Soluti…', 'Horizontal'),
    ('Erasmo Duarte', 'IT Manager', 'Ford Motor Company Brasil Ltda'),
    ('Nicolas Duchesneau', 'Analyst TI', 'Portefeuille Soucy Inc'),
    ('Leah Dudley', 'Senior Marketing Specialist', 'Onapsis Inc.'),
    ('Barbara Duffey', 'VP, North America C…', 'Lakeland Industries Inc'),
    ('Damodhar Dyava', 'SAP SD Manag…', "Bob's Discount Furniture, LLC"),
    ('Willard Dyck', 'Sr. Enterprise…', 'IGM Financial/Financière IGM'),
    ('Jan de Leeuw', 'Executive Director Central Fina…', 'Ingram Micro'),
    ('Erin Earl', 'Executive  Industry Advi…', 'SAP AMERICA, INC.'),
    ('Norihiro Egawa', 'Director', 'ABeam Aystems'),
    ('Kenji Eguchi', 'Basis Consulta…', 'NTT DATA Japan Corporation'),
    ('Onyi Egunjobi', 'Value Advisor Senior', 'SAP Canada'),
    ('Marci Ehrhart', 'Global Practice Leader', 'ADP, Inc.'),
    ('Pauleen Elasio', 'Field Finance, Asia Paci…', 'SAP Philippines, Inc.'),
    ('Mark Elkin', 'SVP, Global Head of Solution…', 'SAP CANADA'),
    ('Stephen Elkins', 'Manager Enterprise Business…', 'Basin Electric'),
    ('Barry Emptage', 'Director, SAP E…', 'RHOMBI HOLDINGS LIMITED'),
    ('Martha Enriquez Carrola', 'Customer Engagement and Ado…', 'SAP Mexico'),
    ('Lander Errasti', 'Director', 'BFS Ingenieria Aplicada S.A. de C.V.'),
    ('Matt Curtin', 'Account Executive', 'OneRail, Inc.'),
    ('Thomas Czichowsky', 'Business Consulting Retail | S…', 'Schwarz IT KG'),
    ('Beth clarkin', 'Director…', 'True Commerce Inc. TrueCommerce'),
    ('Nick DAVIS', 'Global Process Owner Order…', 'Elanco US Inc.'),
    ('Abdelhalim Dadouche', 'SAP Product Specialist', 'Databricks Inc.'),
    ('Chung DaeYoung', 'Head of Enterprise 2', 'SAP Korea Limited'),
    ("Gerardo Dall'Orso", 'Director', 'ADECO AGROPECUARIA S.A.'),
    ('Madhu Raju Dandu', 'Director, Dig…', 'RELEASEOWL PRIVATE LIMITED'),
    ('Nicolas Daniels', 'Global Account Director', 'Mediafly'),
    ('Sushovan Datta', 'Vice President', 'Tech Mahindra (americas) Inc.'),
]

wb = Workbook()
ws = wb.active
ws.title = "Attendees"

headers = ["Name", "Role", "Company"]
ws.append(headers)

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
for cell in ws[1]:
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="left", vertical="center")

BIG4_KEYWORDS = [
    "deloitte", "kpmg", "pricewaterhousecoopers", "pwc",
    "ernst & young", "ey global", "ey strategy", "ey u.s.",
]
DEAL_ADVISOR_KEYWORDS = [
    "mckinsey", "bain & company", "boston consulting", "bcg",
    "bearingpoint", "grant thornton", "lazard", "houlihan lokey",
    "moelis", "evercore", "rothschild", "jefferies", "centerview",
    "greenhill", "guggenheim partners", "j.p morgan", "j.p. morgan",
    "jpmorgan", "morgan stanley", "goldman sachs",
]
RETAIL_CPG_KEYWORDS = [
    # Retail
    "walgreens", "autozone", "wayfair", "home depot", "petsmart",
    "aritzia", "h mart", "crocs", "kontoor brands", "varsity brands",
    "ahold delhaize", "bsn sports", "sharp electronics",
    "sharp corporation", "ralph lauren", "best buy", "walmart",
    "kroger", "costco", "macy", "nordstrom", "lowe's",
    "gardner white furniture", "bob's discount furniture",
    # CPG / Food & Beverage
    "hershey", "pepsico", "tyson foods", "bachoco", "mars",
    "kellanova", "ocean spray", "blommer chocolate", "marathon cheese",
    "maryland & virginia milk", "florida crystals", "associated feed",
    "lakeview farms", "performance food group", "cheney bros",
    "ball horticultural", "colgate", "procter", "unilever",
    "coca-cola", "nestle", "nestlé", "conagra", "constellation brands",
    "sylvamo", "jbs usa", "h-e-b", "danone",
]


def category(company: str):
    c = (company or "").lower()
    if any(k in c for k in BIG4_KEYWORDS):
        return "big4"
    if any(k in c for k in DEAL_ADVISOR_KEYWORDS):
        return "deal_advisor"
    if any(k in c for k in RETAIL_CPG_KEYWORDS):
        return "retail_cpg"
    return None


CATEGORY_FILLS = {
    "retail_cpg": PatternFill(start_color="FFF9C4", end_color="FFF9C4", fill_type="solid"),
    "big4": PatternFill(start_color="FFCDD2", end_color="FFCDD2", fill_type="solid"),
    "deal_advisor": PatternFill(start_color="BBDEFB", end_color="BBDEFB", fill_type="solid"),
}

for row in attendees:
    ws.append(row)
    cat = category(row[2])
    if cat:
        fill = CATEGORY_FILLS[cat]
        for cell in ws[ws.max_row]:
            cell.fill = fill

ws.column_dimensions["A"].width = 32
ws.column_dimensions["B"].width = 42
ws.column_dimensions["C"].width = 42
ws.freeze_panes = "A2"

wb.save("/home/user/test-one/attendees.xlsx")
print(f"Wrote {len(attendees)} attendees to attendees.xlsx")
