from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

attendees = [
    ("YU ARAKAWA", "Consultant", "IBM Japan, Ltd."),
    ("Suli Abas", "Business Development Manager", "NSIGHT, INC."),
    ("Katrina Acebedo", "Data Architect", "The Hershey Company"),
    ("NTT DATA Acuna Delaveau", "Directora Enterprise Solution", "NTT DATA Chile"),
    ("Laura Adare", "Manager/Head of Dept", "State of Louisiana"),
    ("Dhruv Aggarwal", "Partner Business Officer to SAP's Chi…", "SAP SE"),
    ("Yeshu Aggarwal", "Principal Value Advisor", "SAP Canada"),
    ("Mukul Agrawal", "IT Director", "Cimpress USA Incorporated"),
    ("Lucia Aguilar Ledezma", "RISE Business Developer", "SAP Costa Rica, S.A."),
    ("Saritha Aguru", "Service Delivery & Product M…", "Ernst & Young"),
    ("Takuya Akatsuka", "GM", "株式会社リクルート"),
    ("Zia Akbar", "Sr Architect", "Jabil Circuit, Inc. c/o Compaq"),
    ("Ram Akella", "Value Advisor", "SAP AMERICA, INC."),
    ("Kash Al Aziz", "Global Head, Corporate Seg…", "SAP MENA LLC"),
    ("Ebenezer Aladeojebi", "Product Manager", "J.P Morgan Chase & Co."),
    ("Torsten Albert", "VP - Head of CPIT Technology Servic…", "SAP SE"),
    ("Steven Albor Jr", "BTP…", "SAP America Public Sec.(Newtown Sq)"),
    ("Cristian Ali", "PES Head MCLAC", "SAP"),
    ("Dilia Alicea", "Management Support", "SAP America (Miami)"),
    ("Benjamin Alimi", "Director", "Panaya Ltd."),
    ("Mathieu Allard", "VP Finance", "Coveo Solutions Inc."),
    ("Kristen Allman", "Sr. Solution Sales Execut…", "SAP AMERICA, INC."),
    ("Salazar del Rio Alma Aurora", "Functional leader", "Bachoco, S.A. de C.V."),
    ("Aditya Amar", "Senior Softw…", "DOW JONES & COMPANY, INC."),
    ("Shafaqat Ameez", "VP Sales - Enterprise Studios", "Globant, LLC"),
    ("Teja Amerineni", "Cheif Strategic officer", "ReleaseOwl"),
    ("David Amiot", "Managing Director", "Deloitte"),
    ("Barbi Amodeo", "Revenue Man…", "TAMKO Building Products, LLC"),
    ("Anu Anand", "Chief of Staff", "SAP INDIA PVT. LTD."),
    ("Piyush Anandani", "Direct…", "Hewlett Packard Enterprise Company"),
    ("Richard Anderson", "SSE - SCM", "SAP AMERICA, INC."),
    ("Tiffany Anderson", "Manager, SA…", "Carlisle Construction Materials"),
    ("Joni Angkasa", "Regional Head of Growth S…", "SAP ASIA Pte Ltd"),
    ("Sean Antonello", "VP, SAP Analytics", "Improving Toronto Inc."),
    ("Karthik Anupoju", "Business Data Analyst", "KATBOTZ LLC"),
    ("Jamie Anushko", "Value Advisor", "SAP AMERICA, INC."),
    ("Kohei Aoki", "Senior Global Account E…", "SAP Japan Co., Ltd."),
    ("Ali Aouzal", "SAP-SCM Consulta…", "Previan Technologies Inc."),
    ("Amy Arendt", "VP, IT Service &…", "Oldcastle Infrastructure, Inc."),
    ("Melissa Arin", "Marketing & Alliances Manager", "GyanSys, Inc."),
    ("Akin Aritmac", "Chief Sales Officer", "sovanta America Inc."),
    ("Dhanishtha Arora", "Consult…", "Celebal Technologies Americas, Inc."),
    ("Tanya Arora", "Global…", "Celebal Technologies Americas Inc."),
    ("Chris Arthur", "Associate Director - Soluti…", "Collins Aerospace"),
    ("Miguel Artigas", "CEO", "724BC Consulting SAS"),
    ("Sokrates Aslanidis", "Territory Account Manager —…", "Releaseowl Inc"),
    ("Michael Asomaning", "TECHNICAL LEAD", "Defense Logistics Agency"),
    ("Da-Wei Au", "Group Product Manag…", "Autodesk Asia Pte Ltd"),
    ("Kevin Aubrey", "Marketing Lead - AMS", "SecurityBridge GmbH"),
    ("Adib Audi", "Account Executive", "SAP Canada"),
    ("Andreas Axer", "", "WIRTGEN GROUP Branch of John Deere Gmb…"),
    ("Marisol Ayala", "VP, Corporate…", "Inspire Medical Systems, Inc."),
    ("Angel Azat", "Executive Assistant", "SAP AMERICA, INC."),
    ("Deepa B", "Senior Customer Onboarding Advisor", "SAP"),
    ("JP BHATT", "CEO", "ImpactQA"),
    ("Jin Seon Baek", "ERP Manager", "H Mart Companies, Inc."),
    ("Stefan Baeuerle", "SVP | Chief Product Officer, SAP HAN…", "SAP SE"),
    ("Paul Baines", "Programme Direct…", "YORK TELECOM LIMITED"),
    ("Staci Baker", "Director", "PricewaterhouseCoopers LLP"),
    ("Divya Balaji", "Value Advisor", "SAP AMERICA, INC."),
    ("Alvar Baldarrama", "Procurement Consultant", "State of Louisiana"),
    ("Christie Balestra", "Senior Ind…", "SAP America Inc. (Hudson Yards)"),
    ("Mithun Bangad", "Sr Manager Finance IT", "NRG Energy, Inc."),
    ("Sahil Bansal", "Senior Manager", "Tricopp LLC dba CloudPaths"),
    ("Paul Baraniuk", "Global Solution…", "Florida Crystals Corporation"),
    ("Horacio Barbosa", "Proce…", "Techint Cia Tecnica Internacional SACI"),
    ("Devraj Bardhan", "SAP AI Leader", "IBM United Kingdom Limited"),
    ("Paul Barrett", "Senior Manager, Channel Sa…", "SPS Commerce"),
    ("Pam Barrowcliffe", "Product Marketing,…", "SAP Canada - Waterloo"),
    ("Alejandro Basigalup", "Jefe de infraestructura corporativo", "Grupo HZ"),
    ("Martin Bava", "IT Bus…", "Techint Cia Tecnica Internacional SACI"),
    ("Lynn Bayer", "Procurement…", "Securian Financial Group, Inc."),
    ("Justin Beachnau", "Senior Account Exe…", "Pittsburgh, SAP America"),
    ("Benjamin Beberness", "Business Architect", "Proquire LLC"),
    ("Chris Becker", "Director, Finance Tr…", "Cintas Corporation No. 1"),
    ("Andy Bell", "Head of Consulting", "RESULTING LIMITED"),
    ("Carrie Bennett", "SVP, Technology Deli…", "Ascentium Corporation"),
    ("Marissa Bennett", "Director, Global People Solutio…", "PepsiCo, Inc"),
    ("James Benson", "Solutions Sales Executiv…", "SAP AMERICA, INC."),
    ("Dan Berard", "", "International Business Machines Corporation…"),
    ("Ethan Berceli", "Director of Sales Engineer", "Mediafly, Inc"),
    ("Frederic Berg", "VP SAP UI Technologies & Mobile", "SAP SE"),
    ("Nick Berg", "SVP Digital Platforms", "Softserve"),
    ("Elliot Berger", "Managing Partner, bp", "SAP UK Limited"),
    ("Kerry Jo Berger", "Executive Director", "JPMorgan Chase Bank, NA"),
    ("Catalina Bernal", "Seller Partner Manager", "SAP CANADA"),
    ("Kori Betsalel", "Senior accountant executive", "SAP CANADA"),
    ("Pallav Bhatnagar", "Sr. Director", "LTM"),
    ("Nitin Bhide", "Regional Sales lead", "Incture LLC"),
    ("Raja Sekhar Bhomadi", "Manager/Head of Dept", "Verizon Sourcing LLC"),
    ("Marco Bickel", "Vice President IT Program Manage…", "Bayer AG"),
    ("Amos Biegun", "CEO", "Vistex, Inc."),
    ("Alex Birle", "Senior Sales Development", "Confido"),
    ("Justin Bisesi", "Business A…", "The Davey Tree Expert Company"),
    ("Ron Blackburn", "EVP of Sales and GTM", "CloudPaths"),
    ("Eric Blondin", "Head of Business Te…", "SimpleFi Solutions, LLC"),
    ("Matt Blyth", "Vice President, Global Pr…", "SAP AMERICA, INC."),
    ("Sanjeev Bode", "VP", "HCL"),
    ("Arndt-Alexander Boehnert", "Global VP CAS…", "SAP Deutschland SE &Co.KG"),
    ("Beverley Den Boestert", "Director - Technology…", "EY Global Services Ltd"),
    ("Kate Bollard", "Consulting Manager", "Collective Insights"),
    ("Raju Bolledla", "SAP Strategic Advisor", "SAP Australia Pty Ltd"),
    ("Jackson Borges", "RVP Finance & Spend", "SAP International Inc."),
    ("Patrick Boruta", "Partner - Business Consultin…", "Grant Thornton"),
    ("Babs Bouchillon", "NA Tradeshows and Event Manager", "Serrala"),
    ("Megan Boulter", "Director of Strategic…", "The Silicon Partners Inc"),
    ("Kailen Boumal", "Sr. Channel Manger", "ADP, Inc."),
    ("Art Boyd", "SVP Growth Partnerships", "Mirakl"),
    ("Joanne Bradford", "Procurement Data & Capability Manager", "JLR"),
    ("Holger Brammer", "VP AI Ecosystem", "SAP SE"),
    ("Stephen Brandes", "VP of Sales", "Confido"),
    ("Chuck Bratton", "Vice President of Solutions", "FPT USA CORP"),
    ("Gary Braunscheidel", "Chief Technology Offic…", "Baillie Lumber Co Inc"),
    ("Adam Breiterman", "", "Maryland & Virginia Milk Producers Cooperati…"),
    ("Oscar Brennan", "Global Head of Growth for Digital Appli…", "Atos"),
    ("Renee Brewer", "Dir Finc Trans.", "Carrier World Headquarters"),
    ("Tim Brewer", "Technology Solutions Manager", "Corevist, Inc."),
    ("Paul Britter", "SAP Program Mana…", "Caterpillar Logistics, Inc."),
    ("Drew Brooks", "Chief Development Officer", "Ergon"),
    ("Jean-F. Brossard", "Partner & VP Business Development", "DBC"),
    ("Ian Brown", "Field Risk Management", "SAP Canada"),
    ("Jay Brown", "", "ConsultingNetwork Business Solutions, LLC"),
    ("Jesse Brown", "Sr Success Executive", "PartnerTap"),
    ("Michelle Brown", "Director Supply Chain", "Raytheon"),
    ("Mitch Brown", "VP, North America", "Acuiti Labs"),
    ("Holger Bruchelt", "Product Manager", "Microsoft Corporation"),
    ("Eduardo Brunetti", "Value Advisor", "SAP Brasil Ltda."),
    ("Franklin Bruno", "Solution Advisor Manager -…", "SAP Brasil Ltda."),
    ("Renee Bruno", "IT Manager", "Prime Conduit, Inc."),
    ("Ann Bryant", "Director - Financi…", "Old Dominion Freight Line"),
    ("Patricia Buchholz", "Gl…", "SUSE Software Solutions Germany GmbH"),
    ("Sneha Budhwani", "Senior Solution Archi…", "Tricentis Americas, Inc."),
    ("Phillip Budidharma", "IS Mana…", "Charlotte Pipe & Foundry Company"),
    ("Mitchell Burkart", "Sales Director", "Globalsource, Inc."),
    ("Alice Burrell", "Data Analytics Senior Manager", "JLR"),
    ("Eamonn Burton", "TPM", "SAP"),
    ("Erin Buss", "", "Globalsource Information Technology III, Inc."),
    ("Tara Butler-Krgovic", "VP, NA Experience and E…", "SAP AMERICA, INC."),
    ("Shawn Byers", "VP, Digital Product Marketing", "SAPinsider"),
    ("YOUNA CHOI", "Assistant Manager", "sunjin"),
    ("Juan Carlos Caballero", "System Developer M…", "PAN AMERICAN GRAIN"),
    ("Lisa Cabarcos", "America's SAP Allianc…", "Ernst & Young U.S. LLP"),
    ("Bobby Cain", "SVP & CIO - North America", "Schneider Electric"),
    ("Elidan Calvo", "SAP Manager", "Align Technology Inc"),
    ("Phil Cameron", "Growth Officer,…", "SAP NEW ZEALAND LIMITED"),
    ("Stefan Camp Angell", "SAP P…", "Komatsu-Mitsui Maquinarias Perú S.A."),
    ("Mariano Caniglia", "Industry Executive Advis…", "SAP Chile Limitada"),
    ("Amanda Cantu", "Product Manager", "Schneider Electric USA, Inc."),
    ("Seila Carcavilla", "Innovation Manager", "JLR"),
    ("Pat Carmody", "Senior Manag…", "Sharp Electronics Corporation"),
    ("Tyler Carr", "Sr. Capabilities Manag…", "McKinsey & Company"),
    ("Matias Romero Carranza", "Sales Solution Director", "Veritas Prime, LLC"),
    ("Sergio Carriero", "Director", "Bell Canada"),
    ("Chrissy Caruso", "Client Engagement Manag…", "Veritas Prime, LLC"),
    ("Mariana Carvajal", "Mobile App Lead", "SAP AMERICA, INC."),
    ("Gabriele Casalena", "Director", "Aubay Italia S.p.A."),
    ("Sumner Case", "Sales Director", "Syntax Systems Limited"),
    ("Margarita Castillo", "Marketing Director", "SAP AMERICA, INC."),
    ("Sam Castro", "Global Product Marketin…", "SAP AMERICA, INC."),
    ("Vy Cates", "Director, HR PM/Produ…", "Phillips 66 Company"),
    ("William Cdebaca", "Group operations Control…", "Fluor Corporation"),
    ("Donatella Cechet", "Chief Product Expert — Cloud ERP Fi…", "SAP SE"),
    ("Ekta Chadha", "Head of Cloud Delivery,…", "SAP AMERICA, INC."),
    ("Joydeep Chakraborty", "Head of ECS CAA…", "SAP LABS INDIA PVT. LTD."),
    ("Arun Chakravarthi", "Enterprise Account M…", "Kaar Technologies Inc"),
    ("Kamlesh Chalasani", "Vice President, Manufacturing", "Tech Mahindra"),
    ("Greg Chamberland", "IT, Enterprise…", "Ocean Spray Cranberries, Inc."),
    ("Chris Chamberlin", "Relationship Manager", "Moody's Corporation"),
    ("Prasanna Chand", "Director - Enterprise Tech", "Wayfair"),
    ("Srinivasan Chandramohan", "Manager", "Cardinal Health Inc."),
    ("Matt Charleston", "Sr Manager Fi…", "Performance Food Group, Inc."),
    ("Alexandra Charris", "Business Relationsh…", "Softtek Renovation SAS"),
    ("Anirban Chatterjee Chatterjee", "SAP SLED Leader", "IBM Corporation"),
    ("Karan Chauhan", "Life Sciences Solutions", "Cognizant"),
    ("Sanjay Chavan", "Head Enterpri…", "Mahindra & Mahindra Limited"),
    ("Abraham Cherian", "Director Security Govern…", "Kontoor Brands Inc"),
    ("Venu Cherupillil", "Systems Engineer Sr Princi…", "The Home Depot"),
    ("Jeff Cheung", "SAP Platform Ow…", "Ionis Pharmaceuticals, Inc."),
    ("Michelle Chew", "Sr. Project Coordinator", "Marine Atlantic Inc."),
    ("Taiseer Chirakkal", "", "International Business Machines Corporation…"),
    ("Karen Chirico", "Executive Director Enterprise Services", "RTX"),
    ("Will Chisholm", "Project Manager", "Southwest Airlines"),
    ("Flora Choi", "Director, ERP…", "BioMarin Pharmaceutical, Inc."),
    ("JongYun Choi", "Managing Director", "BSG partners"),
    ("Parinda Choksi", "CIO - Enablement", "Ball Horticultural Co."),
    ("Sanjay Choubey", "Global Chief Digital an…", "Sylvamo Corporation"),
    ("Nicolas Christiaen Christiaen", "CEO", "Dealside"),
    ("Saurabh Chug", "Solution Advisor", "SAP AMERICA, INC."),
    ("Yoon Chung", "Solution Engineer Manager", "Precisely"),
    ("Douglas Ciolli", "IT Principal Mana…", "Southern California Edison"),
    ("Tania Cirone-Fenyes", "Sr. Director Alliances", "GyanSys, Inc."),
    ("Odércio Claro", "CIO", "Klabin SA"),
    ("Greg Clausing", "Director SAP COE", "The Andersons, Inc."),
    ("Zach Clement", "", "American Equity Investment Li fe Insurance C…"),
    ("Michael Cobler", "Sr. Account Executive", "Cognitus Ltd"),
    ("Tim Coffey", "Sr. AE", "SAP AMERICA, INC."),
    ("Alinne Cogrossi", "Product Manager, ERP Procure to P…", "Arc'teryx"),
    ("Chad Cohen", "Client Engagement Manger", "Veritas Prime, LLC"),
    ("Allan Colaco", "ERP Transfor…", "HellermannTyton Corporation"),
    ("Colin Cole", "IT Director", "JBS USA Food Company Holdings"),
    ("Clay Coleman", "Global Service Director, BPO", "Wipro Limited"),
    ("Andrew Collins", "SVP ERP Transformation", "BP"),
    ("Kelli Collins", "Project Manager", "BlackJet Marketing"),
    ("Oisin Collins", "Partner", "Deloitte"),
    ("Mark Colosimo", "Director of Strategic Acc…", "The Silicon Partners"),
    ("Tom Coltrain", "Enterprise Architect", "Dominion Energy, Inc."),
    ("Sean Comer", "Senior Project…", "TAMKO Building Products LLC"),
    ("Meena Confait", "Global Business & Engagem…", "SAP MENA LLC"),
    ("Alex Connor", "Senior Develo…", "Lantech.com Coöperatie U.A."),
    ("Adam Conrad", "Bus Proc Architect", "McKesson"),
    ("Eileen Conway", "Global Head Strategic Partnerships", "Qualitest"),
    ("Julie Cooper", "Client Relationship Executive", "BravoTECH"),
    ("Michael Coppola", "VP, Finance & Treasury", "Ashland Inc."),
    ("Juan Correa", "Employee", "Sharp Corporation"),
    ("Manoel Costa", "Demo Solutions Expert", "SAP Brasil Ltda."),
    ("Sophie-Anne Cote", "Finance Director", "Barrette-Chapais"),
    ("Maryanne Coughlin", "Director", "PwC"),
    ("Robert Coutu", "Sr. Accoun…", "System Design Analysis (SDA) inc."),
    ("Julie Craig", "Spon…", "SPARKS MARKETING (EMEA) LIMITED"),
    ("Bill Cranston", "SAP Sales Director", "Techwave"),
    ("Keith Creech", "Director, Enterprise Sales", "SPS Commerce, Inc."),
    ("Philippe Cretier", "Head Finance and Spend Manage…", "Santiago"),
    ("Chris Crosby", "Founder | Managing Partner", "Adoptlab"),
    ("Ademar Crotti Junior", "Principal Technical Cons…", "metaphacts GmbH"),
    ("Ken Crovetti", "Business Development Manager-…", "Vertex, Inc."),
    ("Miguel Cruz", "Gerente de Calidad", "Punta Cana"),
    ("Michael Cugliari", "Senior Account Exec…", "The Silicon Partners Inc"),
    ("Marco Sanna", "", "cbs Corporate Business Solutions Unternehm…"),
    ("Rajesh Sarin", "Global Head - ERP Platf…", "Analog Devices, Inc."),
    ("Subhayu Sarkar", "", "Cognizant Technology Solutions U.S. Corporat…"),
    ("Michael Sass", "VP, IT", "Alphatec Holdings, Inc."),
    ("Yuki Sato", "Business Consulting…", "EY Global Services Ltd"),
    ("Naoya Satomi", "Senior Manager", "NTT DATA Japan Corporation"),
    ("Klaus-Peter Sauer", "Product Manager SAP Business Data…", "SAP SE"),
    ("Vivek Saurabh", "Director of Business Developm…", "GyanSys, Inc."),
    ("Tom Savoie", "Customer Solution Director", "EverBlue Partners"),
    ("Andreas Schaefer", "CRO SCM MEE", "SAP Deutschland SE &Co.KG"),
    ("James Scheel", "Solution Sales Executive…", "SAP AMERICA, INC."),
    ("Ralf Scherer", "Global Transfo…", "SAP Deutschland SE &Co.KG"),
    ("Kathrin Schmalzing", "Partner", "PricewaterhouseCoopers LLP"),
    ("Brian Schmidt", "Principal I.T. Architect", "Mckesson"),
    ("Jan Schneider", "GVP Head of AI Partner Ecosystem", "SAP SE"),
    ("Rebecca Schneider", "Project Consultant", "SAP SE"),
    ("Tonia Schneider", "Principal Accoun…", "Amazon Web Services, Inc."),
    ("Pete Scholtens", "Managing Direc…", "Delaware North America LLC"),
    ("Axel Schroeder", "Chief Architect", "SAP SE"),
    ("Christoph Schroeder", "Global Head, Industry Business Unit…", "SAP SE"),
    ("Carsten Schuetz", "VP, Global He…", "SAP Deutschland SE & Co.KG"),
    ("Michael Schultz", "Value Advisor", "SAP AMERICA, INC."),
    ("Floyd Scott", "Customer Success Ma…", "LG CNS America, Inc."),
    ("Cindy Seaburn", "S…", "The School Board of Duval County Florida"),
    ("Kress Sebastian", "Head of AI, Platforms & Data", "SAP SE"),
    ("Sandeep Sehgal", "Vice-President, SAP Services", "SAP Canada"),
    ("Aparna Seksaria", "Global Director, Life Sciences IBU", "SAP"),
    ("Sam Seth", "GM Retail, Co…", "On Demand Technologies, Inc."),
    ("Rahul Sethi", "Sr. Client Advocate", "Corevist Inc"),
    ("Kanan Sethi Jawa", "Director", "Bombardier Inc."),
    ("JUAN IGNACIO Sevilla", "GERENTE DE PRODUCCIÓN", "plasticaucho"),
    ("Harshal Shah", "CEO", "Elsner Technologies pvt ltd"),
    ("Vinay Shah", "Value Advisor", "SAP"),
    ("Dawn Shakeshaft", "Controller", "Associated Feed & Supply Co."),
    ("Aditya Shankar", "Co-fou…", "Sookti AI Innovations Private Limited"),
    ("Hari Shankar", "Associate Vice Presi…", "Hexaware Technologies"),
    ("Murali Shanmugam", "Business AI Strategy A…", "SAP Australia Pty Ltd"),
    ("Chris Shano", "Marketing Head,…", "ATOS INTERNATIONAL SAS"),
    ("Ashuka Sharma", "VA", "SAP America Inc. (Hudson Yards)"),
    ("Dhruv Sharma", "Assistant Vice Preside…", "Celebal Technologies"),
    ("Priya Sharma", "Glo…", "SNP TRANSFORMATIONS SEA PTE. LTD."),
    ("Shantanu Sharma", "Architecture Advisor", "SAP America (Reston)"),
    ("Suchit Sharma", "Assistan…", "Celebal Technologies Americas Inc."),
    ("Heidi Sheehan", "Vice President, Information Technol…", ""),
    ("Anastasiya Shemanskaya", "CFO Customer Office", "SAP AMERICA, INC."),
    ("Sameer Shepal", "Global Lead - SAP…", "Tata Technologies Limited"),
    ("Colby Sheridan", "Industry Executive Advis…", "SAP AMERICA, INC."),
    ("Scott Sherman", "SVP Information Te…", "The Pittsburgh Paints Co."),
    ("Yasuhiro Shibata", "Department Manager", "JSOL Corporation"),
    ("Allon Shiff Shiff", "Value Advis…", "SAP Industries (Washington DC)"),
    ("Dong Moon Shin", "Manager", "Pan Ocean Co., Ltd."),
    ("Mary Shinn", "Managing Director, SAP K…", "SAP Korea Limited"),
    ("Tomoya Shinozaki", "", "フォーティエンスコンサルティング株式会社…"),
    ("Nobunori Shiono", "IT…", "株式会社ベイカレントコンサルティング"),
    ("Krista Shirley", "Employee", "Expand Energy Corporation"),
    ("Lisa Shober", "Mana…", "Air Products and Chemicals, Inc"),
    ("Olga Shumikhina", "Umoja HCM Team Lead", "The United Nations"),
    ("Andrew Sigler", "Account Director", "Syntax Systems USA LP"),
    ("Mikolaj Sikorski", "Strategic Partner Initiatives", "SAP Ireland Ltd."),
    ("Jonathan Silva", "Instituição de Pagament…", "Nu Pagamentos S.A"),
    ("Renato Silva", "Solutions Sa…", "Globant Brasil Consultoria Ltda"),
    ("Sergei Silva", "", "Vistex"),
    ("Felix Silvagnoli", "SAP Platform Owner", "BP International Limited"),
    ("Gianluca Simeone", "Global SAP CTIO & AI Leader", "Capgemini"),
    ("Cintia Simonelli", "Managing Part…", "SAP Argentina - Buenos Aires"),
    ("Eric Simonson", "Director - Product Marke…", "SAP AMERICA, INC."),
    ("Natalie Singh", "Global Strategic Scale L…", "SAP AMERICA, INC."),
    ("Sukhbir Singh", "S…", "The School Board of Duval County Florida"),
    ("Vikrant Sisodia", "Sr. Product Manager", "Autodesk, Inc."),
    ("David Smith", "VP, Chief Enterprise Ar…", "SAP America (Reston)"),
    ("Rachel Smith", "Partner Sales Manager", "Docusign Inc"),
    ("Mark Smysor", "Business Systems Analyst in Enterpri…", "Utilities"),
    ("Delaiah Snowden", "IT Ana…", "South Florida Water Management Dist"),
    ("Jairo Soares De Matos", "Analyst - SAP Busi…", "Canadian Blood Services"),
    ("Michael Somerville", "Sales Executive", "Checkout.com"),
    ("YoonWon Song", "IT Director", "i-SENS, Inc."),
    ("Dag Terje Sorlie", "Managing Director", "Accenture"),
    ("Thiago Souza", "IT CO…", "MINERACAO SERRAS DO OESTE LTDA"),
    ("Meik Spanowsky", "Director", "PricewaterhouseCoopers LLP"),
    ("Thorsten Spihlmann", "Head of Business Development for T…", "SAP SE"),
    ("TD Srinivasan", "Industry…", "SAP Public Services, Inc. (Hudson Y"),
    ("Mike Stafford", "Senior ABAP Developer", "Titan Ventures LLC"),
    ("Jennifer Stapleton", "VP of Accounting Strategy &…", "American Equity"),
    ("John Stark", "Global Head of SAP Alliance", "Loftware"),
    ("Denis Staudt", "", "GLOBAL DISTRIBUIÇÃO DE BENS DE CONSU…"),
    ("Maximilian Stein", "SAP Product Owner - Treasury CPIT", "SAP SE"),
    ("Amanda Steiner", "Business Process Architect", "McKesson"),
    ("Dieter Steinmann", "", "Fraport AG Frankfurt Airport Services Worldwi…"),
    ("Jorrit Steinz", "Founder & CEO", "ChannelEngine.com"),
    ("Robert Stemmler", "Global Alliances & Ec…", "McKinsey & Company"),
    ("Yonathan Stephanos", "SAP Data & AI Business Group Le…", "Accenture"),
    ("Patrick Stewart", "Account Executive", "SAP AMERICA, INC."),
    ("Jochen Stiebe", "Head of Sales Treas…", "Target-Networks GmbH"),
    ("Leslie Stoffel", "", "CARMEUSE RESEARCH AND TECHNOLOGY S…"),
    ("Miodrag Stojanov", "Lead Engineer", "SEMOS SOFTWARE LLC"),
    ("Bojana Stojanovich", "VP, NA Strategic Partnerships", "Tricentis"),
    ("Seda Strate", "Partner Innovation Lead", "SAP SE"),
    ("Divya Struebing", "Supply Chain Customer…", "SAP AMERICA, INC."),
    ("Kevin Stupp", "Director S4 Platform", "The Hershey Company"),
    ("Harish Subramanian", "Principal Enterprise Arch…", "SAP AMERICA, INC."),
    ("Marc Sudjian", "Enterprise Architect, SAP So…", "Bombardier Inc."),
    ("Hirofumi Sugimoto", "Officer", "ABeam Systems Ltd."),
    ("Michael Sukachev", "Sr. EA", "Teranet Inc"),
    ("Som Suresh", "Man…", "Deloitte Touche Tohmatsu Services, LLC"),
    ("Jain Sushant", "Chief Revenue Officer, F&S…", "SAP ASIA Pte Ltd"),
    ("Scott Sutker", "Vice President Customer Success…", "Alpharetta"),
    ("Mergenthaler Sven", "Global Head of Strategic Central Ser…", "SAP SE"),
    ("Jereme Swoboda", "Segment Director", "Avvale, Inc."),
    ("Debra Syring", "Senior IT Manager", "Entegris, Inc."),
    ("Kai Szatkowski", "Head of Product Sales", "Natuvion GmbH"),
    ("MARCO TOMBOLINI", "Global He…", "DOLCE & GABBANA BEAUTY SRL"),
    ("KAZUSHI TOYOMASU", "Global Direct…", "MOL Chemical Tankers Pte Ltd"),
    ("Stacey Taborelli", "Executive Business Partn…", "SAP AMERICA, INC."),
    ("Ahmed Taher", "IT Director", "Al Daajan Trading"),
    ("Chieko Takahata", "Chief", "BROTHER INDUSTRIES,LTD."),
    ("Arai Takahiro", "Services Delivery Manag…", "SAP Japan Co., Ltd."),
    ("Eiji Takashina", "Associate Director", "Kyndryl Japan KK"),
    ("Tetsushi Takino", "Manager", "大和ハウス工業株式会社"),
    ("Makoto Tamura", "Alliance Group Director", "FUJITSU LIMITED"),
    ("Chiyuki Tanaka", "Team leader", "Recruit Co., Ltd."),
    ("Steve Tanaka", "Sr Vice Presid…", "Blommer Chocolate Company"),
    ("Yasuhiro Tanaka", "Director", "Recuruit Co.,Ltd."),
    ("Kristin Taner", "Chief Marke…", "Vortex Software Consulting, LLC"),
    ("Mitchell Tauer", "Services Account Execut…", "SAP AMERICA, INC."),
    ("Roxanna Tavares", "Director, Gl…", "The Nielsen Company (US), LLC."),
    ("Theo Tavrides", "Vice Presi…", "NTT Data Business Solutions, Inc."),
    ("Jamie Taylor", "Global VP, Strategic Partnerships", "SAP Canada"),
    ("Meghan Taylor", "Industry Account Ex…", "Pittsburgh, SAP America"),
    ("Samantha Taylor", "Senior Solutions Account Exec…", "SAP Canada"),
    ("Sarah Taylor", "Solution Advisor", "SAP AMERICA, INC."),
    ("Jorge Tercero", "Manager/H…", "Asociacion Mutual Sancor Salud"),
    ("Michael Teti", "Architect", "Carlisle Construction Materials"),
    ("Suji Thampi", "Vice President", "MINDSPRINT PTE. LTD."),
    ("Le Thanh Phong", "Managing Direc…", "FPT Japan Holdings Co., Ltd."),
    ("Michael Theis", "Senior Director, Healthcare Life Scien…", "Icertis"),
    ("Rene Theriault", "IT Program Director", "BRP INC"),
    ("Barbara Thrasher", "SR STAFF ARCHITECT", "Tyson Foods, Inc."),
    ("Nissim Titan", "CEO", "4CAST SYSTEMS LTD"),
    ("James Tiwari", "Director", "Intellioz LLC"),
    ("Shuhei Toba", "Manager", "Business Engineering Corporation"),
    ("John Tocci", "", "Cbs Corporate Business Solutions America In…"),
    ("Oliver Toloui", "Director - AI…", "Ibase Operations Corp Qualitest"),
    ("Ray Toma", "Senior Principal — Global Strategic Initia…", "ADP"),
    ("Yuko Tominaga", "Research Writer", "Freelance"),
    ("Laura Tozzo", "AI Product Lead SAP IBP", "SAP SE"),
    ("Eero Traagel", "Partner", "IBM Canada Limited"),
    ("Adam Trahan", "Vice President", "SAP AMERICA, INC."),
    ("Evgeny Treskin", "SAP Alliances Director", "Argano"),
    ("Chetan Tripathi", "oCFO Adoption expert", "SAP"),
    ("Seshagiri Tripurana", "Senior Director", "Johnson & Johnson"),
    ("Masaru Tsukahira", "Director", "TOKYO ELECTRON LIMITED."),
    ("Lindsay Tucker", "Solution Consultant", "Docusign"),
    ("Paul Turbes", "Managing Director", "KPMG LLP"),
    ("Treaver Tyler", "Tech…", "Meijer Great Lakes Limited Partnership"),
    ("Kotaro Ueda", "Chief Operating Officer", "JSUG"),
    ("Rajkishore Una", "President/CEO", "GyanSys, Inc."),
    ("Bala Parameswara Rao Upadhyay…", "Associate Director", "Stefanini, Inc."),
    ("Oscar Uribe", "CFO", "EDUARDONO S A S"),
    ("SACHIN VAIDYA", "Director - Enterprise Commercial…", "Pfizer, Inc."),
    ("Jonathan VON RUEDEN", "Chief AI Officer", "SAP SE"),
    ("Wagner Valentin", "Director of Regulated Indust…", "SAP Brasil Ltda."),
    ("Jorge Valles Velásquez", "KMMP…", "Komatsu-Mitsui Maquinarias Peru S.A."),
    ("Henri Vallet", "VP Sales, Americas B2B", "Mirakl"),
    ("Jeff Van Pelt", "Founder / Managing Dire…", "Javelin Consulting"),
    ("Meredith Van Wyk", "Americas Field Partner…", "SAP AMERICA, INC."),
    ("Joris Van der Donck", "Sr Manag…", "Commscope Connectivity Belgium"),
    ("Vijay Varee", "Senior Manager", "Petsmart LLC"),
    ("Suman Varma", "IT Director", "Cintas Corporation"),
    ("Chris Vassalotti", "Director", "Opentext"),
    ("Raju Vedala", "CEO", "CES Business Technologies, LLC"),
    ("Asier Vega Sanchez", "Implementation Consultant", "Arkyn"),
    ("Jennifer Veillon", "Dir Project Controls", "Fluor Corporation"),
    ("Ajay Reddy Velampudi", "Senior VP - Sa…", "Miracle Software Systems Inc."),
    ("William Velastegui", "JEFE DE TI Y PR…", "Plasticaucho Industrial S.A."),
    ("Rajiv Vemula", "", "Cognizant Technology Solutions U.S. Corporat…"),
    ("Sundu Venkataramani", "Industry Val…", "SAP Industries (Washington DC)"),
    ("Venkat Venkataramani", "VP", "SAP AMERICA, INC."),
    ("Tom Venner-Crysell", "Managing Director", "ERPeople Solutions Ltd"),
    ("Eduardo Vergara", "Manager/Head of Dept", "Agrosuper S.A."),
    ("Amit Verma", "RVP, Head of CFO Advisory…", "SAP ASIA Pte Ltd"),
    ("Kumar Vidit", "Product Marketing M…", "SAP America(Bellevue)"),
    ("Lakshmi Vidyashankar", "VP of IT", "Marvin Engineering Co., Inc."),
    ("Jayant Vikram", "Cloud Delivery Lead", "Accenture LLP"),
    ("Yeni Villanueva", "Supervisora…", "Compañia Minera Antamina S.A."),
    ("Robert Vinyard", "VP and Senior Partner", "IBM"),
    ("Thomas Vioux", "Partner", "PwC"),
    ("Anil Visal", "Partner", "PricewaterhouseCoopers LLP"),
    ("Clara Viscido", "Consulting Services Director", "GEONOSIS"),
    ("Paulo Vita Vita", "", "Get Servicos de Gestao, Tecnologia e Particip…"),
    ("Ranjan Vitt", "AI Compliance Governance Program…", "SAP SE"),
    ("Jose Voisin", "Global CIO", "Carmeuse"),
    ("Christina Volk", "Head of Strate…", "SAP Deutschland SE &Co.KG"),
    ("Jessica Voyles", "Account Executive, South", "SAP AMERICA, INC."),
    ("Sandeep Vyas", "Solutio…", "Incture Technologies Private Limited"),
    ("Thomas von Alm", "SVP Cross-Solution Services", "SAP SE"),
    ("Markus von Quast", "Global Head Industry Ecosystem", "SAP SE"),
    ("TATSUO WATANABE", "Principal Cons…", "D I SQUARE CORPORATION."),
    ("Masayuki Wada", "SVP, Head of Corporate Digit…", "Fujitsu Limited"),
    ("Stephen Wagenheim", "Senior Sales Executive - Suppl…", "Dallas (Allen)"),
    ("Neha Wahi", "Global Alliance Lead", "A.T. Kearney, Inc."),
    ("Waka Wakabayashi", "Associate Partner", "KPMG Consulting Co., Ltd."),
    ("Gustavo Waldfogiel", "LAC HCM Head", "SAP Argentina - Buenos Aires"),
    ("Shashikant Walimbe", "Vice President & Global Head -…", "LTM LIMITED"),
    ("Julie Walker", "Sr. Director, Enterprise Applicatio…", "Armstrong"),
    ("Rob Wallace", "Senior Manager Digital & In…", "Jaguarlandrover"),
    ("Enzhou Wang", "Chief Technology Officer", "City of Tacoma"),
    ("May Wang", "Direc…", "Deloitte Consulting (Shanghai) Co., Ltd."),
    ("Adam Warner", "Cost Analyst", "Marathon Cheese Corporation"),
    ("Kosuke Watanabe", "Senior Account Executive", "SAP Japan Co., Ltd."),
    ("Takashi Watanabe", "執行役員", "JFE Systems,Inc."),
    ("Robert Watson", "Sr Account Executive", "SAP AMERICA, INC."),
    ("Ashley Waxman", "Strategic Sales Executive", "Aevitas IT LLC"),
    ("Christy Weaver", "Global Demand Generation Man…", "Vertex, Inc."),
    ("Mike Weaver", "Senior I…", "True Commerce Inc. TrueCommerce"),
    ("Chris Webster", "SVP IT Strategy & Architecture", "Ahold Delhaize"),
    ("Matt Webster", "Director of…", "Gardner White Furniture Co., Inc."),
    ("Patrick Weil", "IT Director", "Metrie Canada Ltd"),
    ("Sarah Weiler", "Manager, Busine…", "Ball Horticultural Company"),
    ("Adam Werner", "VP, Corporate Technology", "Crocs, Inc."),
    ("Maddie Werner", "Director of Delivery Solutions", "Robra IT"),
    ("Katherine West", "CX Account Executive", "SAP Canada"),
    ("Anja Wettling", "Managing Director", "anuwo GmbH"),
    ("Charleen Wetzstein", "SAP Principal Architect", "PROSPECTOR, LLC"),
    ("Peter Wheatley", "Enterprise Architect…", "SAP America (Houston)"),
    ("Robb White", "", "BSN SPORTS, LLC f/k/n Sports Supply Group,…"),
    ("Peter Widmer", "Chief of Staff to the Global Head of S…", "SAP SE"),
    ("Chad Wiech", "Director of Solution…", "Pittsburgh, SAP America"),
    ("Chamnida Wijetilleke", "Managing Director", "The Ducats Group LLC"),
    ("Pete Wilkins", "NA Partner Manager", "SAP America(Bellevue)"),
    ("Mark Willey", "Vice…", "Deloitte Touche Tohmatsu Services, LLC"),
    ("Ed Williamson", "Client Services Lead", "XMATERIA LTD"),
    ("Monica Willis", "HR Strategy and Value A…", "Plano- Legacy West"),
    ("Charlotte Wilson", "Senior Manager Strategic Cha…", "Direct Energy"),
    ("Emily Wisemiller", "Sr. Data Analyst", "Molex"),
    ("Julia Wolfe", "Analyst Relations Manager", "IBM"),
    ("Jennifer Workman", "Techn…", "Universal Destinations & Experiences"),
    ("Steven Wright Wright", "VP Sales", "Acuiti Labs Limited"),
    ("Monty Wurth", "VP of Operations", "Optima Consulting L.L.C."),
    ("Brad Wylie", "Account Executive", "SAP Canada"),
    ("KAORI YASHIKI", "Business Resear…", "Hitachi Digital Services LLC"),
    ("YOUNGHO YOO", "Team Leader", "LG CNS Co., Ltd."),
    ("Mohamed YUSUF", "Head of Integrated Toolchain", "SAP MENA LLC"),
    ("Hikaru Yafuso", "Senior Alliance Director", "Databricks"),
    ("Sonoko Yamamoto", "Partner Business Manager", "SAP Japan Co., Ltd."),
    ("Osamu Yamazaki", "Co…", "Hitachi Industry & Control Solutions, Ltd."),
    ("Kenji Yanagi", "Group Leader", "ASAHI GROUP JAPAN, LTD."),
    ("EJ Yang", "IT Deputy Director", "MediaTek Inc."),
    ("Kiran Yarlagadda Yarlagadda", "Managing…", "Adroix Corp DBA CodeForce 360"),
    ("Takayuki Yasuda", "sales", "JFE Systems, Inc."),
    ("Tomoki Yasuda", "AssistantMana…", "NTT DATA Japan Corporation"),
    ("Kazuhiro Yonekawa", "Chief/Proj…", "CANON MARKETING JAPAN INC.,"),
    ("Sungeui Yoon", "Senior Specialist", "Microsoft"),
    ("Christopher Yope", "SAP Supply C…", "DXC Technology Services LLC"),
    ("Kohei Yoshimatsu", "Manager", "アズビル株式会社"),
    ("taichi yoshida", "Senior Ma…", "BENIC SOLUTION CORPORATION"),
    ("nakajima yuki", "Member", "Nitori Co., Ltd."),
    ("Stefan Zach", "VP Global IT", "Wieland Group"),
    ("Beau Zaremski", "VP of Sales", "SAP AMERICA, INC."),
    ("Yuan Zhang", "Senior Project Manager, SAP AI RIG", "SAP SE"),
    ("Cathy Zhou", "IT Director, EBS", "Ecolab Inc."),
    ("Gustavo Zintak", "Manager/Head of Dept", "SWISS MEDICAL S.A."),
    ("Alina Zuberi", "Global Content Strategist", "SAP MENA LLC"),
    ("Yoshiaki Agata 縣", "consultant", "AJS株式会社"),
    ("裕紀 阿保", "Manager", "FORTIENCE CONSULTING INC."),
    ("謙介 青木", "Manager, Uvance Market Developme…", "Fujitsu"),
    ("Sriram Hariharasubramanian", "Partner, Tech Consult…", "EY Global Services Ltd"),
    ("Lori Harner", "Global Vice President, Pr…", "SAP AMERICA, INC."),
    ("Melissa Harris", "IT Program Manager", "Masco Corporation"),
    ("Paul Harris", "Senior Director, SAP Basi…", "Varsity Brands, LLC."),
    ("Joe Hartnett", "Sales Director", "OpenText"),
    ("Richard Hatton", "VP Platform Engin…", "NBCUniversal Media, LLC"),
    ("Kishie Hattori", "Chief Partner Officer", "SAP Japan Co., Ltd."),
    ("Chelsea Hebb", "Director, Cons…", "Collective Insights Consulting"),
    ("Heiko Hecht", "President", "IBIS America Inc."),
    ("Tess Heiligers", "Business Advisor to SVP ERP Tranfo…", "BP P.L.C."),
    ("Christian Heinrich", "Chief Solutions Officer & Membe…", "sovanta AG"),
    ("VALERIAN HARRIS", "Vice President", "HCL America Solutions Inc."),
    ("Angie Halderman", "Vice President, Sales", "Deloitte"),
    ("Sarah Haley-Fuentes", "Director of Solution Engineering", "Vistex Inc."),
    ("Callie Hall", "", "SAP Global Marketing"),
    ("Deborah Hamilton", "Head of Global Marketing", "Bristlecone, Inc."),
    ("Joe Hamilton", "Sr. Director AME Mfg. Technology", "Honeywell"),
    ("Sean Hamlin", "Value Advisor", "SAP AMERICA, INC."),
    ("Youngshin Han", "IT Team Manager", "i-SENS. Inc"),
    ("Rebecca Hanna", "Head of Services, ANZ", "SAP AUSTRALIA"),
    ("Manoj Harbhajanka", "CEO", "Acuiti Labs Limited"),
    ("Hadi Hares", "Global Lead Product Manager", "SAP SE"),
    ("Ajay Gupta", "Mana…", "Reliance Comfort Limited Partnership"),
    ("Anupam Gupta Gupta", "President", "Celebal Technologies Americas, Inc."),
    ("Niladri Gupta", "Managing Director", "Deloitte Consulting LLP"),
    ("Piyush Gupta", "Global Head -…", "Celebal Technologies Pvt Ltd."),
    ("Raj Gupta", "Managing Director", "Intellioz LLC"),
    ("Varun Gupta", "", "American Water Works Service Company, Inc.…"),
    ("Vishal Gupta", "Head of Finance & Spe…", "SAP Australia Pty Ltd"),
    ("David Gust", "Account Executive", "SAP AMERICA, INC."),
    ("Nestor Guzman", "Dire…", "Aerovias Del Continente Americano S.A."),
    ("Kalman Gyula", "", "BSN SPORTS, LLC f/k/n Sports Supply Group,…"),
    ("Karthik Gobi gobimayilsamygound…", "Service Owner (…", "Honeywell International Inc"),
    ("Nicole Griffith", "Sr. Director, SAP Alliance", "Protera"),
    ("Tim Grochowski", "Senior Cloud Executive", "SAP AMERICA, INC."),
    ("Anette Grossmueller", "Head of Cross Product Management,…", "SAP SE"),
    ("Scott Groth", "Directir, ERP Architect", "Pfizer, Inc."),
    ("John Grzybek", "Senior SAP Projec…", "Fujitsu North America, Inc."),
    ("Rodolfo Guerrero", "Account Manager", "GBM Dominicana"),
    ("Alex Guglielmetti", "VP - IT Advisor", "Pantexan Deterrence"),
    ("Patricia Guillermo", "It Lead", "Kellanova/Mars"),
    ("Dmitri Guinzbourg", "Team Lead/Supervisor", "Air Canada"),
    ("Timothy Guizon", "Finance Manager", "Henry Company LLC"),
    ("Moises Gonzalez", "Client Engagement Manag…", "Veritas Prime, LLC"),
    ("Oziel Gonzalez", "VA Head Mexico", "SAP Mexico"),
    ("Nelson González", "Subgerente e Operaciones…", "Grupo Kaufmann"),
    ("Senthil Gopalan", "D-1 (SVP", "The United Nations"),
    ("Pooven Govender", "APAC CLOUD ARCHITE…", "SAP Australia Pty Ltd"),
    ("Christine Graham", "Chief Information Officer", "Lakeview Farms, LLC"),
    ("Geoff Gray", "Head of Product", "The Config Team"),
    ("Andrew Greaves", "Sen…", "SAPOCOM Technologies Private Limited"),
    ("Samuel Grenade", "", "Coveo Solutions Inc"),
    ("Betsy Griffin", "Senior Account Executive", "SAP AMERICA, INC."),
    ("Paula Griffin", "Seni…", "Medical College of Virginia Foundation"),
]

wb = Workbook()
ws = wb.active
ws.title = "Attendees"

headers = ["Name", "Role", "Company"]
ws.append(headers)

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
for cell in ws[1]:
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="left", vertical="center")

for row in attendees:
    ws.append(row)

ws.column_dimensions["A"].width = 32
ws.column_dimensions["B"].width = 42
ws.column_dimensions["C"].width = 42
ws.freeze_panes = "A2"

wb.save("/home/user/test-one/attendees.xlsx")
print(f"Wrote {len(attendees)} attendees to attendees.xlsx")
