from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

attendees = [
    ("YU ARAKAWA", "Consultant", "IBM Japan, Ltd."),
    ("Suli Abas", "Business Development Manager", "NSIGHT, INC."),
    ("Katrina Acebedo", "Data Architect", "The Hershey Company"),
    ("NTT DATA Acuna Delaveau", "Directora Enterprise Solution", "NTT DATA Chile"),
    ("Laura Adare", "Manager/Head of Dept", "State of Louisiana"),
    ("Dhruv Aggarwal", "Partner Business Officer to SAP's Chi…", "SAP SE"),
    ("Yeshu Aggarwal", "Principal Value Advisor", "SAP Canada"),
    ("Mukul Agrawal", "IT Director", "Cimpress USA Incorporated"),
    ("Lucia Aguilar Ledezma", "RISE Business Developer", "SAP Costa Rica, S.A."),
    ("Saritha Aguru", "Service Delivery & Product M…", "Ernst & Young"),
    ("Takuya Akatsuka", "GM", "株式会社リクルート"),
    ("Zia Akbar", "Sr Architect", "Jabil Circuit, Inc. c/o Compaq"),
    ("Ram Akella", "Value Advisor", "SAP AMERICA, INC."),
    ("Kash Al Aziz", "Global Head, Corporate Seg…", "SAP MENA LLC"),
    ("Ebenezer Aladeojebi", "Product Manager", "J.P Morgan Chase & Co."),
    ("Torsten Albert", "VP - Head of CPIT Technology Servic…", "SAP SE"),
    ("Steven Albor Jr", "BTP…", "SAP America Public Sec.(Newtown Sq)"),
    ("Cristian Ali", "PES Head MCLAC", "SAP"),
    ("Dilia Alicea", "Management Support", "SAP America (Miami)"),
    ("Benjamin Alimi", "Director", "Panaya Ltd."),
    ("Mathieu Allard", "VP Finance", "Coveo Solutions Inc."),
    ("Kristen Allman", "Sr. Solution Sales Execut…", "SAP AMERICA, INC."),
    ("Salazar del Rio Alma Aurora", "Functional leader", "Bachoco, S.A. de C.V."),
    ("Aditya Amar", "Senior Softw…", "DOW JONES & COMPANY, INC."),
    ("Shafaqat Ameez", "VP Sales - Enterprise Studios", "Globant, LLC"),
    ("Teja Amerineni", "Cheif Strategic officer", "ReleaseOwl"),
    ("David Amiot", "Managing Director", "Deloitte"),
    ("Barbi Amodeo", "Revenue Man…", "TAMKO Building Products, LLC"),
    ("Anu Anand", "Chief of Staff", "SAP INDIA PVT. LTD."),
    ("Piyush Anandani", "Direct…", "Hewlett Packard Enterprise Company"),
    ("Richard Anderson", "SSE - SCM", "SAP AMERICA, INC."),
    ("Tiffany Anderson", "Manager, SA…", "Carlisle Construction Materials"),
    ("Joni Angkasa", "Regional Head of Growth S…", "SAP ASIA Pte Ltd"),
    ("Sean Antonello", "VP, SAP Analytics", "Improving Toronto Inc."),
    ("Karthik Anupoju", "Business Data Analyst", "KATBOTZ LLC"),
    ("Jamie Anushko", "Value Advisor", "SAP AMERICA, INC."),
    ("Kohei Aoki", "Senior Global Account E…", "SAP Japan Co., Ltd."),
    ("Ali Aouzal", "SAP-SCM Consulta…", "Previan Technologies Inc."),
    ("Amy Arendt", "VP, IT Service &…", "Oldcastle Infrastructure, Inc."),
    ("Melissa Arin", "Marketing & Alliances Manager", "GyanSys, Inc."),
    ("Akin Aritmac", "Chief Sales Officer", "sovanta America Inc."),
    ("Dhanishtha Arora", "Consult…", "Celebal Technologies Americas, Inc."),
    ("Tanya Arora", "Global…", "Celebal Technologies Americas Inc."),
    ("Chris Arthur", "Associate Director - Soluti…", "Collins Aerospace"),
    ("Miguel Artigas", "CEO", "724BC Consulting SAS"),
    ("Sokrates Aslanidis", "Territory Account Manager —…", "Releaseowl Inc"),
    ("Michael Asomaning", "TECHNICAL LEAD", "Defense Logistics Agency"),
    ("Da-Wei Au", "Group Product Manag…", "Autodesk Asia Pte Ltd"),
    ("Kevin Aubrey", "Marketing Lead - AMS", "SecurityBridge GmbH"),
    ("Adib Audi", "Account Executive", "SAP Canada"),
    ("Andreas Axer", "", "WIRTGEN GROUP Branch of John Deere Gmb…"),
    ("Marisol Ayala", "VP, Corporate…", "Inspire Medical Systems, Inc."),
    ("Angel Azat", "Executive Assistant", "SAP AMERICA, INC."),
    ("Deepa B", "Senior Customer Onboarding Advisor", "SAP"),
    ("JP BHATT", "CEO", "ImpactQA"),
    ("Jin Seon Baek", "ERP Manager", "H Mart Companies, Inc."),
    ("Stefan Baeuerle", "SVP | Chief Product Officer, SAP HAN…", "SAP SE"),
    ("Paul Baines", "Programme Direct…", "YORK TELECOM LIMITED"),
    ("Staci Baker", "Director", "PricewaterhouseCoopers LLP"),
    ("Divya Balaji", "Value Advisor", "SAP AMERICA, INC."),
    ("Alvar Baldarrama", "Procurement Consultant", "State of Louisiana"),
    ("Christie Balestra", "Senior Ind…", "SAP America Inc. (Hudson Yards)"),
    ("Mithun Bangad", "Sr Manager Finance IT", "NRG Energy, Inc."),
    ("Sahil Bansal", "Senior Manager", "Tricopp LLC dba CloudPaths"),
    ("Paul Baraniuk", "Global Solution…", "Florida Crystals Corporation"),
    ("Horacio Barbosa", "Proce…", "Techint Cia Tecnica Internacional SACI"),
    ("Devraj Bardhan", "SAP AI Leader", "IBM United Kingdom Limited"),
    ("Paul Barrett", "Senior Manager, Channel Sa…", "SPS Commerce"),
    ("Pam Barrowcliffe", "Product Marketing,…", "SAP Canada - Waterloo"),
    ("Alejandro Basigalup", "Jefe de infraestructura corporativo", "Grupo HZ"),
    ("Martin Bava", "IT Bus…", "Techint Cia Tecnica Internacional SACI"),
    ("Lynn Bayer", "Procurement…", "Securian Financial Group, Inc."),
    ("Justin Beachnau", "Senior Account Exe…", "Pittsburgh, SAP America"),
    ("Benjamin Beberness", "Business Architect", "Proquire LLC"),
    ("Chris Becker", "Director, Finance Tr…", "Cintas Corporation No. 1"),
    ("Andy Bell", "Head of Consulting", "RESULTING LIMITED"),
    ("Carrie Bennett", "SVP, Technology Deli…", "Ascentium Corporation"),
    ("Marissa Bennett", "Director, Global People Solutio…", "PepsiCo, Inc"),
    ("James Benson", "Solutions Sales Executiv…", "SAP AMERICA, INC."),
    ("Dan Berard", "", "International Business Machines Corporation…"),
    ("Ethan Berceli", "Director of Sales Engineer", "Mediafly, Inc"),
    ("Frederic Berg", "VP SAP UI Technologies & Mobile", "SAP SE"),
    ("Nick Berg", "SVP Digital Platforms", "Softserve"),
    ("Elliot Berger", "Managing Partner, bp", "SAP UK Limited"),
    ("Kerry Jo Berger", "Executive Director", "JPMorgan Chase Bank, NA"),
    ("Catalina Bernal", "Seller Partner Manager", "SAP CANADA"),
    ("Kori Betsalel", "Senior accountant executive", "SAP CANADA"),
    ("Pallav Bhatnagar", "Sr. Director", "LTM"),
    ("Nitin Bhide", "Regional Sales lead", "Incture LLC"),
    ("Raja Sekhar Bhomadi", "Manager/Head of Dept", "Verizon Sourcing LLC"),
    ("Marco Bickel", "Vice President IT Program Manage…", "Bayer AG"),
    ("Amos Biegun", "CEO", "Vistex, Inc."),
    ("Alex Birle", "Senior Sales Development", "Confido"),
    ("Justin Bisesi", "Business A…", "The Davey Tree Expert Company"),
    ("Ron Blackburn", "EVP of Sales and GTM", "CloudPaths"),
    ("Eric Blondin", "Head of Business Te…", "SimpleFi Solutions, LLC"),
    ("Matt Blyth", "Vice President, Global Pr…", "SAP AMERICA, INC."),
    ("Sanjeev Bode", "VP", "HCL"),
    ("Arndt-Alexander Boehnert", "Global VP CAS…", "SAP Deutschland SE &Co.KG"),
    ("Beverley Den Boestert", "Director - Technology…", "EY Global Services Ltd"),
    ("Kate Bollard", "Consulting Manager", "Collective Insights"),
    ("Raju Bolledla", "SAP Strategic Advisor", "SAP Australia Pty Ltd"),
    ("Jackson Borges", "RVP Finance & Spend", "SAP International Inc."),
    ("Patrick Boruta", "Partner - Business Consultin…", "Grant Thornton"),
    ("Babs Bouchillon", "NA Tradeshows and Event Manager", "Serrala"),
    ("Megan Boulter", "Director of Strategic…", "The Silicon Partners Inc"),
    ("Kailen Boumal", "Sr. Channel Manger", "ADP, Inc."),
    ("Art Boyd", "SVP Growth Partnerships", "Mirakl"),
    ("Joanne Bradford", "Procurement Data & Capability Manager", "JLR"),
    ("Holger Brammer", "VP AI Ecosystem", "SAP SE"),
    ("Stephen Brandes", "VP of Sales", "Confido"),
    ("Chuck Bratton", "Vice President of Solutions", "FPT USA CORP"),
    ("Gary Braunscheidel", "Chief Technology Offic…", "Baillie Lumber Co Inc"),
    ("Adam Breiterman", "", "Maryland & Virginia Milk Producers Cooperati…"),
    ("Oscar Brennan", "Global Head of Growth for Digital Appli…", "Atos"),
    ("Renee Brewer", "Dir Finc Trans.", "Carrier World Headquarters"),
    ("Tim Brewer", "Technology Solutions Manager", "Corevist, Inc."),
    ("Paul Britter", "SAP Program Mana…", "Caterpillar Logistics, Inc."),
    ("Drew Brooks", "Chief Development Officer", "Ergon"),
    ("Jean-F. Brossard", "Partner & VP Business Development", "DBC"),
    ("Ian Brown", "Field Risk Management", "SAP Canada"),
    ("Jay Brown", "", "ConsultingNetwork Business Solutions, LLC"),
    ("Jesse Brown", "Sr Success Executive", "PartnerTap"),
    ("Michelle Brown", "Director Supply Chain", "Raytheon"),
    ("Mitch Brown", "VP, North America", "Acuiti Labs"),
    ("Holger Bruchelt", "Product Manager", "Microsoft Corporation"),
    ("Eduardo Brunetti", "Value Advisor", "SAP Brasil Ltda."),
    ("Franklin Bruno", "Solution Advisor Manager -…", "SAP Brasil Ltda."),
    ("Renee Bruno", "IT Manager", "Prime Conduit, Inc."),
    ("Ann Bryant", "Director - Financi…", "Old Dominion Freight Line"),
    ("Patricia Buchholz", "Gl…", "SUSE Software Solutions Germany GmbH"),
    ("Sneha Budhwani", "Senior Solution Archi…", "Tricentis Americas, Inc."),
    ("Phillip Budidharma", "IS Mana…", "Charlotte Pipe & Foundry Company"),
    ("Mitchell Burkart", "Sales Director", "Globalsource, Inc."),
    ("Alice Burrell", "Data Analytics Senior Manager", "JLR"),
    ("Eamonn Burton", "TPM", "SAP"),
    ("Erin Buss", "", "Globalsource Information Technology III, Inc."),
    ("Tara Butler-Krgovic", "VP, NA Experience and E…", "SAP AMERICA, INC."),
    ("Shawn Byers", "VP, Digital Product Marketing", "SAPinsider"),
    ("YOUNA CHOI", "Assistant Manager", "sunjin"),
    ("Juan Carlos Caballero", "System Developer M…", "PAN AMERICAN GRAIN"),
    ("Lisa Cabarcos", "America's SAP Allianc…", "Ernst & Young U.S. LLP"),
    ("Bobby Cain", "SVP & CIO - North America", "Schneider Electric"),
    ("Elidan Calvo", "SAP Manager", "Align Technology Inc"),
    ("Phil Cameron", "Growth Officer,…", "SAP NEW ZEALAND LIMITED"),
    ("Stefan Camp Angell", "SAP P…", "Komatsu-Mitsui Maquinarias Perú S.A."),
    ("Mariano Caniglia", "Industry Executive Advis…", "SAP Chile Limitada"),
    ("Amanda Cantu", "Product Manager", "Schneider Electric USA, Inc."),
    ("Seila Carcavilla", "Innovation Manager", "JLR"),
    ("Pat Carmody", "Senior Manag…", "Sharp Electronics Corporation"),
    ("Tyler Carr", "Sr. Capabilities Manag…", "McKinsey & Company"),
    ("Matias Romero Carranza", "Sales Solution Director", "Veritas Prime, LLC"),
    ("Sergio Carriero", "Director", "Bell Canada"),
    ("Chrissy Caruso", "Client Engagement Manag…", "Veritas Prime, LLC"),
    ("Mariana Carvajal", "Mobile App Lead", "SAP AMERICA, INC."),
    ("Gabriele Casalena", "Director", "Aubay Italia S.p.A."),
    ("Sumner Case", "Sales Director", "Syntax Systems Limited"),
    ("Margarita Castillo", "Marketing Director", "SAP AMERICA, INC."),
    ("Sam Castro", "Global Product Marketin…", "SAP AMERICA, INC."),
    ("Vy Cates", "Director, HR PM/Produ…", "Phillips 66 Company"),
    ("William Cdebaca", "Group operations Control…", "Fluor Corporation"),
    ("Donatella Cechet", "Chief Product Expert — Cloud ERP Fi…", "SAP SE"),
    ("Anirban Chatterjee Chatterjee", "SAP SLED Leader", "IBM Corporation"),
    ("Karan Chauhan", "Life Sciences Solutions", "Cognizant"),
    ("Sanjay Chavan", "Head Enterpri…", "Mahindra & Mahindra Limited"),
    ("Abraham Cherian", "Director Security Govern…", "Kontoor Brands Inc"),
    ("Venu Cherupillil", "Systems Engineer Sr Princi…", "The Home Depot"),
    ("Jeff Cheung", "SAP Platform Ow…", "Ionis Pharmaceuticals, Inc."),
    ("Michelle Chew", "Sr. Project Coordinator", "Marine Atlantic Inc."),
    ("Taiseer Chirakkal", "", "International Business Machines Corporation…"),
    ("Karen Chirico", "Executive Director Enterprise Services", "RTX"),
    ("Will Chisholm", "Project Manager", "Southwest Airlines"),
    ("Flora Choi", "Director, ERP…", "BioMarin Pharmaceutical, Inc."),
    ("JongYun Choi", "Managing Director", "BSG partners"),
    ("Parinda Choksi", "CIO - Enablement", "Ball Horticultural Co."),
    ("Sanjay Choubey", "Global Chief Digital an…", "Sylvamo Corporation"),
    ("Nicolas Christiaen Christiaen", "CEO", "Dealside"),
    ("Saurabh Chug", "Solution Advisor", "SAP AMERICA, INC."),
    ("Yoon Chung", "Solution Engineer Manager", "Precisely"),
    ("Douglas Ciolli", "IT Principal Mana…", "Southern California Edison"),
    ("Tania Cirone-Fenyes", "Sr. Director Alliances", "GyanSys, Inc."),
    ("Odércio Claro", "CIO", "Klabin SA"),
    ("Greg Clausing", "Director SAP COE", "The Andersons, Inc."),
    ("Zach Clement", "", "American Equity Investment Li fe Insurance C…"),
    ("Michael Cobler", "Sr. Account Executive", "Cognitus Ltd"),
    ("Tim Coffey", "Sr. AE", "SAP AMERICA, INC."),
    ("Alinne Cogrossi", "Product Manager, ERP Procure to P…", "Arc'teryx"),
    ("Chad Cohen", "Client Engagement Manger", "Veritas Prime, LLC"),
    ("Allan Colaco", "ERP Transfor…", "HellermannTyton Corporation"),
    ("Colin Cole", "IT Director", "JBS USA Food Company Holdings"),
    ("Clay Coleman", "Global Service Director, BPO", "Wipro Limited"),
    ("Andrew Collins", "SVP ERP Transformation", "BP"),
    ("Kelli Collins", "Project Manager", "BlackJet Marketing"),
    ("Oisin Collins", "Partner", "Deloitte"),
    ("Mark Colosimo", "Director of Strategic Acc…", "The Silicon Partners"),
    ("Tom Coltrain", "Enterprise Architect", "Dominion Energy, Inc."),
    ("Sean Comer", "Senior Project…", "TAMKO Building Products LLC"),
    ("Meena Confait", "Global Business & Engagem…", "SAP MENA LLC"),
    ("Alex Connor", "Senior Develo…", "Lantech.com Coöperatie U.A."),
    ("Adam Conrad", "Bus Proc Architect", "McKesson"),
    ("Eileen Conway", "Global Head Strategic Partnerships", "Qualitest"),
    ("Julie Cooper", "Client Relationship Executive", "BravoTECH"),
    ("Michael Coppola", "VP, Finance & Treasury", "Ashland Inc."),
    ("Juan Correa", "Employee", "Sharp Corporation"),
    ("Manoel Costa", "Demo Solutions Expert", "SAP Brasil Ltda."),
    ("Sophie-Anne Cote", "Finance Director", "Barrette-Chapais"),
    ("Maryanne Coughlin", "Director", "PwC"),
    ("Robert Coutu", "Sr. Accoun…", "System Design Analysis (SDA) inc."),
    ("Julie Craig", "Spon…", "SPARKS MARKETING (EMEA) LIMITED"),
    ("Bill Cranston", "SAP Sales Director", "Techwave"),
    ("Keith Creech", "Director, Enterprise Sales", "SPS Commerce, Inc."),
    ("Philippe Cretier", "Head Finance and Spend Manage…", "Santiago"),
    ("Chris Crosby", "Founder | Managing Partner", "Adoptlab"),
    ("Ademar Crotti Junior", "Principal Technical Cons…", "metaphacts GmbH"),
    ("Ken Crovetti", "Business Development Manager-…", "Vertex, Inc."),
    ("Miguel Cruz", "Gerente de Calidad", "Punta Cana"),
    ("Michael Cugliari", "Senior Account Exec…", "The Silicon Partners Inc"),
]

wb = Workbook()
ws = wb.active
ws.title = "Attendees"

headers = ["Name", "Role", "Company"]
ws.append(headers)

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
for cell in ws[1]:
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="left", vertical="center")

for row in attendees:
    ws.append(row)

ws.column_dimensions["A"].width = 32
ws.column_dimensions["B"].width = 42
ws.column_dimensions["C"].width = 42
ws.freeze_panes = "A2"

wb.save("/home/user/test-one/attendees.xlsx")
print(f"Wrote {len(attendees)} attendees to attendees.xlsx")
